import { getCityConfigSync } from "./city";

export interface Topic {
  id: string;
  name: string;
  nameNl: string;
  nameFr: string;
  nameDe: string;
  nameEs: string;
  description: string;
  descriptionNl: string;
  descriptionFr: string;
  descriptionDe: string;
  descriptionEs: string;
}

export interface Angle {
  id: string;
  name: string;
  nameNl: string;
  nameFr: string;
  nameDe: string;
  nameEs: string;
  description: string;
  descriptionNl: string;
  descriptionFr: string;
  descriptionDe: string;
  descriptionEs: string;
  icon: string;
}

export interface Theme {
  id: string;
  name: string;
  nameNl: string;
  nameFr: string;
  nameDe: string;
  nameEs: string;
  icon: string;
  iconFamily: "Ionicons" | "MaterialIcons" | "MaterialCommunityIcons" | "Feather";
  iconImage?: any;
  color: string;
  topics: Topic[];
  angles?: Angle[];
}

const parisThemes: Theme[] = [
  {
    id: "history",
    name: "History",
    nameNl: "Geschiedenis",
    nameFr: "Histoire",
    nameDe: "Geschichte",
    nameEs: "Historia",
    icon: "book",
    iconFamily: "Ionicons",
    iconImage: require("@/assets/images/category-history.png"),
    color: "#6B4226",
    topics: [
      {
        id: "founding-lutetia",
        name: "Lutetia: The Birth of Paris",
        nameNl: "Lutetia: De Geboorte van Parijs",
        nameFr: "Lutèce : La Naissance de Paris",
        nameDe: "Lutetia: Die Geburt von Paris",
        nameEs: "Lutecia: El Nacimiento de París",
        description: "How a small Roman settlement on the Seine became one of the world's greatest cities",
        descriptionNl: "Hoe een kleine Romeinse nederzetting aan de Seine uitgroeide tot een van de grootste steden ter wereld",
        descriptionFr: "Comment une petite colonie romaine sur la Seine est devenue l'une des plus grandes villes du monde",
        descriptionDe: "Wie eine kleine römische Siedlung an der Seine zu einer der größten Städte der Welt wurde",
        descriptionEs: "Cómo un pequeño asentamiento romano en el Sena se convirtió en una de las ciudades más grandes del mundo",
      },
      {
        id: "medieval-paris",
        name: "Medieval Paris: Rise of a Capital",
        nameNl: "Middeleeuws Parijs: Opkomst van een Hoofdstad",
        nameFr: "Paris médiéval : L'essor d'une capitale",
        nameDe: "Mittelalterliches Paris: Aufstieg einer Hauptstadt",
        nameEs: "París medieval: El ascenso de una capital",
        description: "From Viking sieges to the building of Notre-Dame, how Paris became the heart of France",
        descriptionNl: "Van Vikingbelegeringen tot de bouw van Notre-Dame, hoe Parijs het hart van Frankrijk werd",
        descriptionFr: "Des sièges vikings à la construction de Notre-Dame, comment Paris est devenu le cœur de la France",
        descriptionDe: "Von Wikingerbelagerungen bis zum Bau von Notre-Dame, wie Paris das Herz Frankreichs wurde",
        descriptionEs: "De los asedios vikingos a la construcción de Notre-Dame, cómo París se convirtió en el corazón de Francia",
      },
      {
        id: "paris-kings",
        name: "City of Kings",
        nameNl: "Stad der Koningen",
        nameFr: "La Cité des Rois",
        nameDe: "Stadt der Könige",
        nameEs: "Ciudad de Reyes",
        description: "The monarchs who shaped Paris from the Capetians to the Sun King's Versailles",
        descriptionNl: "De vorsten die Parijs vormden, van de Capetingen tot de Zonnekoning in Versailles",
        descriptionFr: "Les monarques qui ont façonné Paris, des Capétiens au Versailles du Roi-Soleil",
        descriptionDe: "Die Monarchen, die Paris prägten, von den Kapetingern bis zum Versailles des Sonnenkönigs",
        descriptionEs: "Los monarcas que moldearon París, desde los Capetos hasta el Versalles del Rey Sol",
      },
      {
        id: "haussmann-transformation",
        name: "The Great Transformation",
        nameNl: "De Grote Transformatie",
        nameFr: "La Grande Transformation",
        nameDe: "Die Große Transformation",
        nameEs: "La Gran Transformación",
        description: "How Baron Haussmann demolished medieval Paris and created the city of grand boulevards",
        descriptionNl: "Hoe Baron Haussmann het middeleeuwse Parijs sloopte en de stad van grote boulevards creëerde",
        descriptionFr: "Comment le baron Haussmann a démoli le Paris médiéval et créé la ville des grands boulevards",
        descriptionDe: "Wie Baron Haussmann das mittelalterliche Paris abriss und die Stadt der großen Boulevards schuf",
        descriptionEs: "Cómo el barón Haussmann demolió el París medieval y creó la ciudad de los grandes bulevares",
      },
      {
        id: "paris-catacombs",
        name: "The Paris Catacombs",
        nameNl: "De Catacomben van Parijs",
        nameFr: "Les Catacombes de Paris",
        nameDe: "Die Katakomben von Paris",
        nameEs: "Las Catacumbas de París",
        description: "The underground realm of the dead beneath the streets of Paris",
        descriptionNl: "Het ondergrondse dodenrijk onder de straten van Parijs",
        descriptionFr: "Le royaume souterrain des morts sous les rues de Paris",
        descriptionDe: "Das unterirdische Totenreich unter den Straßen von Paris",
        descriptionEs: "El reino subterráneo de los muertos bajo las calles de París",
      },
      {
        id: "knights-templar",
        name: "The Knights Templar in Paris",
        nameNl: "De Tempeliers in Parijs",
        nameFr: "Les Templiers à Paris",
        nameDe: "Die Tempelritter in Paris",
        nameEs: "Los Templarios en París",
        description: "The mysterious order and their powerful Parisian stronghold in the Marais",
        descriptionNl: "De mysterieuze orde en hun machtige Parijse burcht in de Marais",
        descriptionFr: "L'ordre mystérieux et leur puissante forteresse parisienne dans le Marais",
        descriptionDe: "Der geheimnisvolle Orden und ihre mächtige Pariser Festung im Marais",
        descriptionEs: "La misteriosa orden y su poderosa fortaleza parisina en el Marais",
      },
      {
        id: "plague-years",
        name: "The Plague Years",
        nameNl: "De Pestjaren",
        nameFr: "Les Années de Peste",
        nameDe: "Die Pestjahre",
        nameEs: "Los Años de la Peste",
        description: "How the Black Death ravaged medieval Paris and changed the city forever",
        descriptionNl: "Hoe de Zwarte Dood het middeleeuwse Parijs teisterde en de stad voorgoed veranderde",
        descriptionFr: "Comment la Peste Noire a ravagé le Paris médiéval et changé la ville à jamais",
        descriptionDe: "Wie der Schwarze Tod das mittelalterliche Paris verwüstete und die Stadt für immer veränderte",
        descriptionEs: "Cómo la Peste Negra devastó el París medieval y cambió la ciudad para siempre",
      },
      {
        id: "joan-of-arc",
        name: "Joan of Arc and Paris",
        nameNl: "Jeanne d'Arc en Parijs",
        nameFr: "Jeanne d'Arc et Paris",
        nameDe: "Johanna von Orléans und Paris",
        nameEs: "Juana de Arco y París",
        description: "The warrior saint's failed siege of Paris and the battle for the city",
        descriptionNl: "De mislukte belegering van Parijs door de heilige strijdster en de strijd om de stad",
        descriptionFr: "Le siège raté de Paris par la sainte guerrière et la bataille pour la ville",
        descriptionDe: "Die gescheiterte Belagerung von Paris durch die Heilige Kriegerin und der Kampf um die Stadt",
        descriptionEs: "El fallido asedio de París por la santa guerrera y la batalla por la ciudad",
      },
    ],
  },
  {
    id: "revolution",
    name: "French Revolution",
    nameNl: "Franse Revolutie",
    nameFr: "Révolution française",
    nameDe: "Französische Revolution",
    nameEs: "Revolución Francesa",
    icon: "flag",
    iconFamily: "Ionicons",
    iconImage: require("@/assets/images/category-french-revolution.png"),
    color: "#C0392B",
    angles: [
      {
        id: "historical",
        name: "Historical",
        nameNl: "Historisch",
        nameFr: "Historique",
        nameDe: "Historisch",
        nameEs: "Histórico",
        description: "Facts, dates, and chronological storytelling",
        descriptionNl: "Feiten, data en chronologisch vertellen",
        descriptionFr: "Faits, dates et récit chronologique",
        descriptionDe: "Fakten, Daten und chronologisches Erzählen",
        descriptionEs: "Hechos, fechas y narración cronológica",
        icon: "book-open",
      },
      {
        id: "personal-stories",
        name: "Personal Stories",
        nameNl: "Persoonlijke Verhalen",
        nameFr: "Histoires personnelles",
        nameDe: "Persönliche Geschichten",
        nameEs: "Historias personales",
        description: "The story told from the iconic figures involved",
        descriptionNl: "Het verhaal verteld vanuit de iconische figuren die erbij betrokken waren",
        descriptionFr: "L'histoire racontée du point de vue des personnages emblématiques",
        descriptionDe: "Die Geschichte aus der Perspektive der beteiligten ikonischen Figuren",
        descriptionEs: "La historia contada desde las figuras icónicas involucradas",
        icon: "users",
      },
    ],
    topics: [
      {
        id: "bastille",
        name: "The Storming of the Bastille",
        nameNl: "De Bestorming van de Bastille",
        nameFr: "La Prise de la Bastille",
        nameDe: "Der Sturm auf die Bastille",
        nameEs: "La Toma de la Bastilla",
        description: "The iconic event that sparked the revolution on July 14, 1789",
        descriptionNl: "De iconische gebeurtenis die de revolutie op 14 juli 1789 in gang zette",
        descriptionFr: "L'événement iconique qui a déclenché la révolution le 14 juillet 1789",
        descriptionDe: "Das ikonische Ereignis, das am 14. Juli 1789 die Revolution auslöste",
        descriptionEs: "El evento icónico que desencadenó la revolución el 14 de julio de 1789",
      },
      {
        id: "bastille-walk",
        name: "Walking Tour: Place de la Bastille",
        nameNl: "Wandeltour: Place de la Bastille",
        nameFr: "Visite à pied : Place de la Bastille",
        nameDe: "Rundgang: Place de la Bastille",
        nameEs: "Paseo guiado: Place de la Bastille",
        description: "Walk the grounds where the fortress once stood and trace the revolution's first steps",
        descriptionNl: "Wandel over de plek waar het fort ooit stond en volg de eerste stappen van de revolutie",
        descriptionFr: "Parcourez les lieux où la forteresse se dressait et retracez les premiers pas de la révolution",
        descriptionDe: "Gehen Sie über das Gelände, auf dem einst die Festung stand, und verfolgen Sie die ersten Schritte der Revolution",
        descriptionEs: "Recorre el terreno donde se alzaba la fortaleza y sigue los primeros pasos de la revolución",
      },
      {
        id: "marie-antoinette",
        name: "Marie Antoinette: The Last Queen",
        nameNl: "Marie Antoinette: De Laatste Koningin",
        nameFr: "Marie-Antoinette : La Dernière Reine",
        nameDe: "Marie Antoinette: Die letzte Königin",
        nameEs: "María Antonieta: La Última Reina",
        description: "The tragic queen whose life became a symbol of royal excess",
        descriptionNl: "De tragische koningin wier leven een symbool werd van koninklijke buitensporigheid",
        descriptionFr: "La reine tragique dont la vie est devenue un symbole de l'excès royal",
        descriptionDe: "Die tragische Königin, deren Leben zum Symbol königlicher Verschwendung wurde",
        descriptionEs: "La trágica reina cuya vida se convirtió en símbolo del exceso real",
      },
      {
        id: "danton",
        name: "Danton: Voice of the People",
        nameNl: "Danton: Stem van het Volk",
        nameFr: "Danton : La Voix du Peuple",
        nameDe: "Danton: Stimme des Volkes",
        nameEs: "Danton: La Voz del Pueblo",
        description: "The fiery orator who shaped the revolution and lost his head to it",
        descriptionNl: "De vurige redenaar die de revolutie vormde en er zijn hoofd bij verloor",
        descriptionFr: "L'orateur fougueux qui a façonné la révolution et y a perdu la tête",
        descriptionDe: "Der feurige Redner, der die Revolution formte und dabei seinen Kopf verlor",
        descriptionEs: "El fogoso orador que moldeó la revolución y perdió la cabeza por ella",
      },
      {
        id: "reign-of-terror",
        name: "The Reign of Terror",
        nameNl: "Het Schrikbewind",
        nameFr: "La Terreur",
        nameDe: "Die Schreckensherrschaft",
        nameEs: "El Reinado del Terror",
        description: "The dark period of mass executions under Robespierre",
        descriptionNl: "De donkere periode van massaexecuties onder Robespierre",
        descriptionFr: "La sombre période d'exécutions de masse sous Robespierre",
        descriptionDe: "Die dunkle Zeit der Massenhinrichtungen unter Robespierre",
        descriptionEs: "El oscuro período de ejecuciones masivas bajo Robespierre",
      },
      {
        id: "conciergerie-walk",
        name: "Walking Tour: The Conciergerie",
        nameNl: "Wandeltour: De Conciergerie",
        nameFr: "Visite à pied : La Conciergerie",
        nameDe: "Rundgang: Die Conciergerie",
        nameEs: "Paseo guiado: La Conciergerie",
        description: "Visit the medieval prison where Marie Antoinette spent her final days",
        descriptionNl: "Bezoek de middeleeuwse gevangenis waar Marie Antoinette haar laatste dagen doorbracht",
        descriptionFr: "Visitez la prison médiévale où Marie-Antoinette a passé ses derniers jours",
        descriptionDe: "Besuchen Sie das mittelalterliche Gefängnis, in dem Marie Antoinette ihre letzten Tage verbrachte",
        descriptionEs: "Visita la prisión medieval donde María Antonieta pasó sus últimos días",
      },
      {
        id: "napoleon",
        name: "Napoleon's Rise to Power",
        nameNl: "De Opkomst van Napoleon",
        nameFr: "L'Ascension de Napoléon",
        nameDe: "Napoleons Aufstieg zur Macht",
        nameEs: "El Ascenso de Napoleón al Poder",
        description: "From revolutionary general to Emperor of France",
        descriptionNl: "Van revolutionair generaal tot keizer van Frankrijk",
        descriptionFr: "De général révolutionnaire à empereur de France",
        descriptionDe: "Vom revolutionären General zum Kaiser von Frankreich",
        descriptionEs: "De general revolucionario a emperador de Francia",
      },
      {
        id: "charlotte-corday",
        name: "Charlotte Corday: The Assassin",
        nameNl: "Charlotte Corday: De Moordenares",
        nameFr: "Charlotte Corday : L'Assassine",
        nameDe: "Charlotte Corday: Die Attentäterin",
        nameEs: "Charlotte Corday: La Asesina",
        description: "The young woman who murdered Marat in his bathtub and changed history",
        descriptionNl: "De jonge vrouw die Marat in zijn badkuip vermoordde en de geschiedenis veranderde",
        descriptionFr: "La jeune femme qui a assassiné Marat dans sa baignoire et changé l'histoire",
        descriptionDe: "Die junge Frau, die Marat in seiner Badewanne ermordete und die Geschichte veränderte",
        descriptionEs: "La joven mujer que asesinó a Marat en su bañera y cambió la historia",
      },
    ],
  },
  {
    id: "museums",
    name: "Museums",
    nameNl: "Musea",
    nameFr: "Musées",
    nameDe: "Museen",
    nameEs: "Museos",
    icon: "museum",
    iconFamily: "MaterialIcons",
    iconImage: require("@/assets/images/category-museums.png"),
    color: "#2980B9",
    angles: [
      {
        id: "origin",
        name: "Origin of the Museum",
        nameNl: "Ontstaan van het Museum",
        nameFr: "Origine du Musée",
        nameDe: "Ursprung des Museums",
        nameEs: "Origen del Museo",
        description: "The founding story and how the museum came to be",
        descriptionNl: "Het ontstaansverhaal en hoe het museum tot stand kwam",
        descriptionFr: "L'histoire de sa fondation et comment le musée est né",
        descriptionDe: "Die Gründungsgeschichte und wie das Museum entstand",
        descriptionEs: "La historia de su fundación y cómo nació el museo",
        icon: "clock",
      },
      {
        id: "prominent-art",
        name: "Prominent Art Pieces",
        nameNl: "Prominente Kunstwerken",
        nameFr: "Œuvres d'art emblématiques",
        nameDe: "Bedeutende Kunstwerke",
        nameEs: "Obras de arte destacadas",
        description: "The most famous and significant works in the collection",
        descriptionNl: "De beroemdste en belangrijkste werken in de collectie",
        descriptionFr: "Les œuvres les plus célèbres et les plus importantes de la collection",
        descriptionDe: "Die berühmtesten und bedeutendsten Werke der Sammlung",
        descriptionEs: "Las obras más famosas e importantes de la colección",
        icon: "image",
      },
      {
        id: "architecture",
        name: "Architecture & Building",
        nameNl: "Architectuur & Gebouw",
        nameFr: "Architecture & Bâtiment",
        nameDe: "Architektur & Gebäude",
        nameEs: "Arquitectura & Edificio",
        description: "The architectural story and design of the building itself",
        descriptionNl: "Het architectuurverhaal en het ontwerp van het gebouw zelf",
        descriptionFr: "L'histoire architecturale et le design du bâtiment lui-même",
        descriptionDe: "Die architektonische Geschichte und Gestaltung des Gebäudes selbst",
        descriptionEs: "La historia arquitectónica y el diseño del edificio en sí",
        icon: "home",
      },
    ],
    topics: [
      {
        id: "louvre",
        name: "The Louvre",
        nameNl: "Het Louvre",
        nameFr: "Le Louvre",
        nameDe: "Der Louvre",
        nameEs: "El Louvre",
        description: "The world's largest art museum and its hidden stories",
        descriptionNl: "Het grootste kunstmuseum ter wereld en zijn verborgen verhalen",
        descriptionFr: "Le plus grand musée d'art du monde et ses histoires cachées",
        descriptionDe: "Das größte Kunstmuseum der Welt und seine verborgenen Geschichten",
        descriptionEs: "El museo de arte más grande del mundo y sus historias ocultas",
      },
      {
        id: "orsay",
        name: "Musée d'Orsay",
        nameNl: "Musée d'Orsay",
        nameFr: "Musée d'Orsay",
        nameDe: "Musée d'Orsay",
        nameEs: "Museo de Orsay",
        description: "From train station to impressionist masterpiece collection",
        descriptionNl: "Van treinstation tot collectie impressionistische meesterwerken",
        descriptionFr: "D'une gare à une collection de chefs-d'œuvre impressionnistes",
        descriptionDe: "Vom Bahnhof zur Sammlung impressionistischer Meisterwerke",
        descriptionEs: "De estación de tren a colección de obras maestras impresionistas",
      },
      {
        id: "pompidou",
        name: "Centre Pompidou",
        nameNl: "Centre Pompidou",
        nameFr: "Centre Pompidou",
        nameDe: "Centre Pompidou",
        nameEs: "Centro Pompidou",
        description: "The inside-out building that revolutionized modern art",
        descriptionNl: "Het binnenstebuiten gebouw dat moderne kunst revolutioneerde",
        descriptionFr: "Le bâtiment à l'envers qui a révolutionné l'art moderne",
        descriptionDe: "Das auf links gedrehte Gebäude, das die moderne Kunst revolutionierte",
        descriptionEs: "El edificio al revés que revolucionó el arte moderno",
      },
      {
        id: "orangerie",
        name: "Musée de l'Orangerie",
        nameNl: "Musée de l'Orangerie",
        nameFr: "Musée de l'Orangerie",
        nameDe: "Musée de l'Orangerie",
        nameEs: "Museo de la Orangerie",
        description: "Monet's Water Lilies and the intimate world of impressionism",
        descriptionNl: "Monets Waterlelies en de intieme wereld van het impressionisme",
        descriptionFr: "Les Nymphéas de Monet et le monde intime de l'impressionnisme",
        descriptionDe: "Monets Seerosen und die intime Welt des Impressionismus",
        descriptionEs: "Los Nenúfares de Monet y el mundo íntimo del impresionismo",
      },
      {
        id: "bourse-commerce",
        name: "Bourse de Commerce",
        nameNl: "Bourse de Commerce",
        nameFr: "Bourse de Commerce",
        nameDe: "Bourse de Commerce",
        nameEs: "Bolsa de Comercio",
        description: "Pinault's contemporary art collection in a stunning 18th-century rotunda",
        descriptionNl: "Pinaults hedendaagse kunstcollectie in een prachtige 18e-eeuwse rotonde",
        descriptionFr: "La collection d'art contemporain de Pinault dans une magnifique rotonde du XVIIIe siècle",
        descriptionDe: "Pinaults zeitgenössische Kunstsammlung in einer atemberaubenden Rotunde aus dem 18. Jahrhundert",
        descriptionEs: "La colección de arte contemporáneo de Pinault en una impresionante rotonda del siglo XVIII",
      },
      {
        id: "rodin",
        name: "Rodin Museum",
        nameNl: "Rodin Museum",
        nameFr: "Musée Rodin",
        nameDe: "Rodin-Museum",
        nameEs: "Museo Rodin",
        description: "The sculptor's mansion and the story of The Thinker",
        descriptionNl: "Het herenhuis van de beeldhouwer en het verhaal van De Denker",
        descriptionFr: "Le manoir du sculpteur et l'histoire du Penseur",
        descriptionDe: "Das Herrenhaus des Bildhauers und die Geschichte des Denkers",
        descriptionEs: "La mansión del escultor y la historia de El Pensador",
      },
      {
        id: "fondation-lv",
        name: "Fondation Louis Vuitton",
        nameNl: "Fondation Louis Vuitton",
        nameFr: "Fondation Louis Vuitton",
        nameDe: "Fondation Louis Vuitton",
        nameEs: "Fundación Louis Vuitton",
        description: "Frank Gehry's spectacular glass sails housing world-class contemporary art in the Bois de Boulogne",
        descriptionNl: "Frank Gehry's spectaculaire glazen zeilen met hedendaagse topkunst in het Bois de Boulogne",
        descriptionFr: "Les spectaculaires voiles de verre de Frank Gehry abritant de l'art contemporain de classe mondiale dans le Bois de Boulogne",
        descriptionDe: "Frank Gehrys spektakuläre Glassegel mit zeitgenössischer Weltklasse-Kunst im Bois de Boulogne",
        descriptionEs: "Las espectaculares velas de cristal de Frank Gehry que albergan arte contemporáneo de clase mundial en el Bois de Boulogne",
      },
      {
        id: "musee-carnavalet",
        name: "Musée Carnavalet",
        nameNl: "Musée Carnavalet",
        nameFr: "Musée Carnavalet",
        nameDe: "Musée Carnavalet",
        nameEs: "Museo Carnavalet",
        description: "The oldest museum of Paris telling the city's story from prehistory to present day",
        descriptionNl: "Het oudste museum van Parijs dat het verhaal van de stad vertelt van prehistorie tot heden",
        descriptionFr: "Le plus ancien musée de Paris racontant l'histoire de la ville de la préhistoire à nos jours",
        descriptionDe: "Das älteste Museum von Paris, das die Geschichte der Stadt von der Vorgeschichte bis heute erzählt",
        descriptionEs: "El museo más antiguo de París que cuenta la historia de la ciudad desde la prehistoria hasta hoy",
      },
    ],
  },
  {
    id: "epic-buildings",
    name: "Epic Buildings",
    nameNl: "Iconische Gebouwen",
    nameFr: "Bâtiments emblématiques",
    nameDe: "Ikonische Bauwerke",
    nameEs: "Edificios emblemáticos",
    icon: "business",
    iconFamily: "MaterialIcons",
    iconImage: require("@/assets/images/category-epic-buildings.png"),
    color: "#34495E",
    topics: [
      {
        id: "eiffel-tower",
        name: "The Eiffel Tower",
        nameNl: "De Eiffeltoren",
        nameFr: "La Tour Eiffel",
        nameDe: "Der Eiffelturm",
        nameEs: "La Torre Eiffel",
        description: "From controversial iron eyesore to the world's most beloved landmark",
        descriptionNl: "Van controversieel ijzeren gedrocht tot het meest geliefde monument ter wereld",
        descriptionFr: "De verrue de fer controversée au monument le plus aimé du monde",
        descriptionDe: "Vom umstrittenen Eisenmonstrum zum beliebtesten Wahrzeichen der Welt",
        descriptionEs: "De controvertida monstruosidad de hierro al monumento más querido del mundo",
      },
      {
        id: "notre-dame",
        name: "Notre-Dame Cathedral",
        nameNl: "Kathedraal Notre-Dame",
        nameFr: "Cathédrale Notre-Dame",
        nameDe: "Kathedrale Notre-Dame",
        nameEs: "Catedral de Notre-Dame",
        description: "Eight centuries of faith, fire, and resurrection on the Île de la Cité",
        descriptionNl: "Acht eeuwen geloof, vuur en wederopstanding op het Île de la Cité",
        descriptionFr: "Huit siècles de foi, de feu et de résurrection sur l'Île de la Cité",
        descriptionDe: "Acht Jahrhunderte Glaube, Feuer und Auferstehung auf der Île de la Cité",
        descriptionEs: "Ocho siglos de fe, fuego y resurrección en la Île de la Cité",
      },
      {
        id: "louvre-palace",
        name: "The Louvre Palace",
        nameNl: "Het Paleis van het Louvre",
        nameFr: "Le Palais du Louvre",
        nameDe: "Der Louvre-Palast",
        nameEs: "El Palacio del Louvre",
        description: "From medieval fortress to royal palace to the world's greatest museum",
        descriptionNl: "Van middeleeuws fort tot koninklijk paleis tot het grootste museum ter wereld",
        descriptionFr: "De forteresse médiévale à palais royal, puis au plus grand musée du monde",
        descriptionDe: "Von der mittelalterlichen Festung zum Königspalast zum größten Museum der Welt",
        descriptionEs: "De fortaleza medieval a palacio real y al museo más grande del mundo",
      },
      {
        id: "sacre-coeur",
        name: "Sacré-Cœur Basilica",
        nameNl: "Basiliek Sacré-Cœur",
        nameFr: "Basilique du Sacré-Cœur",
        nameDe: "Basilika Sacré-Cœur",
        nameEs: "Basílica del Sacré-Cœur",
        description: "The white dome on the hilltop and the turbulent history behind it",
        descriptionNl: "De witte koepel op de heuvel en de turbulente geschiedenis erachter",
        descriptionFr: "Le dôme blanc au sommet de la colline et l'histoire tumultueuse qui se cache derrière",
        descriptionDe: "Die weiße Kuppel auf dem Hügel und die turbulente Geschichte dahinter",
        descriptionEs: "La cúpula blanca en la cima de la colina y la turbulenta historia detrás de ella",
      },
      {
        id: "arc-de-triomphe",
        name: "Arc de Triomphe",
        nameNl: "Arc de Triomphe",
        nameFr: "Arc de Triomphe",
        nameDe: "Arc de Triomphe",
        nameEs: "Arco de Triunfo",
        description: "Napoleon's monument to military glory at the heart of the Champs-Élysées",
        descriptionNl: "Napoleons monument voor militaire glorie in het hart van de Champs-Élysées",
        descriptionFr: "Le monument de Napoléon à la gloire militaire au cœur des Champs-Élysées",
        descriptionDe: "Napoleons Denkmal des militärischen Ruhms im Herzen der Champs-Élysées",
        descriptionEs: "El monumento de Napoleón a la gloria militar en el corazón de los Campos Elíseos",
      },
      {
        id: "pantheon",
        name: "The Panthéon",
        nameNl: "Het Panthéon",
        nameFr: "Le Panthéon",
        nameDe: "Das Panthéon",
        nameEs: "El Panteón",
        description: "Where France honors its greatest citizens, from Voltaire to Marie Curie",
        descriptionNl: "Waar Frankrijk zijn grootste burgers eert, van Voltaire tot Marie Curie",
        descriptionFr: "Où la France honore ses plus grands citoyens, de Voltaire à Marie Curie",
        descriptionDe: "Wo Frankreich seine größten Bürger ehrt, von Voltaire bis Marie Curie",
        descriptionEs: "Donde Francia honra a sus más grandes ciudadanos, de Voltaire a Marie Curie",
      },
      {
        id: "opera-garnier",
        name: "Opéra Garnier",
        nameNl: "Opéra Garnier",
        nameFr: "Opéra Garnier",
        nameDe: "Opéra Garnier",
        nameEs: "Ópera Garnier",
        description: "The lavish palace of opera and the legend of the Phantom",
        descriptionNl: "Het weelderige operapaleis en de legende van het Spook",
        descriptionFr: "Le somptueux palais de l'opéra et la légende du Fantôme",
        descriptionDe: "Der prachtvolle Opernpalast und die Legende des Phantoms",
        descriptionEs: "El lujoso palacio de la ópera y la leyenda del Fantasma",
      },
      {
        id: "palace-versailles",
        name: "Palace of Versailles",
        nameNl: "Paleis van Versailles",
        nameFr: "Château de Versailles",
        nameDe: "Schloss Versailles",
        nameEs: "Palacio de Versalles",
        description: "The Sun King's masterpiece of power, excess, and absolute beauty",
        descriptionNl: "Het meesterwerk van de Zonnekoning vol macht, overdaad en absolute schoonheid",
        descriptionFr: "Le chef-d'œuvre du Roi-Soleil, fait de pouvoir, d'excès et de beauté absolue",
        descriptionDe: "Das Meisterwerk des Sonnenkönigs aus Macht, Überfluss und absoluter Schönheit",
        descriptionEs: "La obra maestra del Rey Sol de poder, exceso y belleza absoluta",
      },
    ],
  },
  {
    id: "modern-history",
    name: "Modern History",
    nameNl: "Moderne Geschiedenis",
    nameFr: "Histoire moderne",
    nameDe: "Moderne Geschichte",
    nameEs: "Historia moderna",
    icon: "history",
    iconFamily: "MaterialIcons",
    iconImage: require("@/assets/images/category-modern-history.png"),
    color: "#8E44AD",
    topics: [
      {
        id: "wwii-paris",
        name: "Paris during World War II",
        nameNl: "Parijs tijdens de Tweede Wereldoorlog",
        nameFr: "Paris pendant la Seconde Guerre mondiale",
        nameDe: "Paris während des Zweiten Weltkriegs",
        nameEs: "París durante la Segunda Guerra Mundial",
        description: "Occupation, resistance, and the fight for liberation",
        descriptionNl: "Bezetting, verzet en de strijd om bevrijding",
        descriptionFr: "Occupation, résistance et combat pour la libération",
        descriptionDe: "Besatzung, Widerstand und der Kampf um die Befreiung",
        descriptionEs: "Ocupación, resistencia y la lucha por la liberación",
      },
      {
        id: "liberation",
        name: "The Liberation of Paris",
        nameNl: "De Bevrijding van Parijs",
        nameFr: "La Libération de Paris",
        nameDe: "Die Befreiung von Paris",
        nameEs: "La Liberación de París",
        description: "August 1944 and the dramatic fight to free the city",
        descriptionNl: "Augustus 1944 en de dramatische strijd om de stad te bevrijden",
        descriptionFr: "Août 1944 et le combat dramatique pour libérer la ville",
        descriptionDe: "August 1944 und der dramatische Kampf um die Befreiung der Stadt",
        descriptionEs: "Agosto de 1944 y la dramática lucha por liberar la ciudad",
      },
      {
        id: "resistance-walk",
        name: "Walking Tour: Resistance Paris",
        nameNl: "Wandeltour: Verzets-Parijs",
        nameFr: "Visite à pied : Paris de la Résistance",
        nameDe: "Rundgang: Widerstandsorte in Paris",
        nameEs: "Paseo guiado: París de la Resistencia",
        description: "Walk past secret meeting points, hidden refuges, and memorials of the French Resistance",
        descriptionNl: "Loop langs geheime ontmoetingsplekken, schuilplaatsen en monumenten van het Franse Verzet",
        descriptionFr: "Passez devant les points de rencontre secrets, les refuges cachés et les mémoriaux de la Résistance française",
        descriptionDe: "Gehen Sie vorbei an geheimen Treffpunkten, versteckten Zufluchtsstätten und Gedenkstätten des französischen Widerstands",
        descriptionEs: "Pasa por puntos de encuentro secretos, refugios ocultos y monumentos de la Resistencia francesa",
      },
      {
        id: "jean-moulin",
        name: "Jean Moulin: Hero of the Resistance",
        nameNl: "Jean Moulin: Held van het Verzet",
        nameFr: "Jean Moulin : Héros de la Résistance",
        nameDe: "Jean Moulin: Held des Widerstands",
        nameEs: "Jean Moulin: Héroe de la Resistencia",
        description: "The prefect who unified the French Resistance and paid the ultimate price",
        descriptionNl: "De prefect die het Franse Verzet verenigde en de ultieme prijs betaalde",
        descriptionFr: "Le préfet qui a unifié la Résistance française et en a payé le prix ultime",
        descriptionDe: "Der Präfekt, der den französischen Widerstand vereinte und den höchsten Preis zahlte",
        descriptionEs: "El prefecto que unificó la Resistencia francesa y pagó el precio más alto",
      },
      {
        id: "may-1968",
        name: "May 1968 Student Protests",
        nameNl: "De Studentenprotesten van Mei 1968",
        nameFr: "Les Manifestations étudiantes de Mai 1968",
        nameDe: "Die Studentenproteste vom Mai 1968",
        nameEs: "Las Protestas estudiantiles de Mayo de 1968",
        description: "When students and workers nearly toppled the government",
        descriptionNl: "Toen studenten en arbeiders bijna de regering ten val brachten",
        descriptionFr: "Quand étudiants et travailleurs ont failli renverser le gouvernement",
        descriptionDe: "Als Studenten und Arbeiter fast die Regierung stürzten",
        descriptionEs: "Cuando estudiantes y trabajadores casi derrocaron al gobierno",
      },
      {
        id: "belle-epoque",
        name: "Paris in the Belle Époque",
        nameNl: "Parijs in de Belle Époque",
        nameFr: "Paris à la Belle Époque",
        nameDe: "Paris in der Belle Époque",
        nameEs: "París en la Belle Époque",
        description: "The golden age of art, culture, and Parisian life",
        descriptionNl: "De gouden eeuw van kunst, cultuur en het Parijse leven",
        descriptionFr: "L'âge d'or de l'art, de la culture et de la vie parisienne",
        descriptionDe: "Das goldene Zeitalter der Kunst, Kultur und des Pariser Lebens",
        descriptionEs: "La edad de oro del arte, la cultura y la vida parisina",
      },
      {
        id: "haussmann",
        name: "Haussmann: The Man Who Rebuilt Paris",
        nameNl: "Haussmann: De Man Die Parijs Herbouwde",
        nameFr: "Haussmann : L'Homme qui a reconstruit Paris",
        nameDe: "Haussmann: Der Mann, der Paris neu erbaute",
        nameEs: "Haussmann: El Hombre que reconstruyó París",
        description: "How one prefect demolished medieval Paris and created the city of boulevards",
        descriptionNl: "Hoe één prefect middeleeuws Parijs sloopte en de stad van boulevards creëerde",
        descriptionFr: "Comment un préfet a démoli le Paris médiéval et créé la ville des boulevards",
        descriptionDe: "Wie ein Präfekt das mittelalterliche Paris abriss und die Stadt der Boulevards schuf",
        descriptionEs: "Cómo un prefecto demolió el París medieval y creó la ciudad de los bulevares",
      },
      {
        id: "paris-expo-1900",
        name: "The 1900 World's Fair",
        nameNl: "De Wereldtentoonstelling van 1900",
        nameFr: "L'Exposition universelle de 1900",
        nameDe: "Die Weltausstellung von 1900",
        nameEs: "La Exposición Universal de 1900",
        description: "The grand exposition that showcased Paris as the capital of the modern world",
        descriptionNl: "De grote tentoonstelling die Parijs presenteerde als hoofdstad van de moderne wereld",
        descriptionFr: "La grande exposition qui a présenté Paris comme la capitale du monde moderne",
        descriptionDe: "Die große Ausstellung, die Paris als Hauptstadt der modernen Welt präsentierte",
        descriptionEs: "La gran exposición que presentó a París como la capital del mundo moderno",
      },
    ],
  },
  {
    id: "neighborhoods",
    name: "Neighborhoods",
    nameNl: "Wijken",
    nameFr: "Quartiers",
    nameDe: "Stadtviertel",
    nameEs: "Barrios",
    icon: "map",
    iconFamily: "Feather",
    iconImage: require("@/assets/images/category-neighborhoods.png"),
    color: "#27AE60",
    angles: [
      {
        id: "historical",
        name: "Historical",
        nameNl: "Historisch",
        nameFr: "Historique",
        nameDe: "Historisch",
        nameEs: "Histórico",
        description: "The origins and historical evolution of this neighborhood",
        descriptionNl: "De oorsprong en historische ontwikkeling van deze buurt",
        descriptionFr: "Les origines et l'évolution historique de ce quartier",
        descriptionDe: "Die Ursprünge und die historische Entwicklung dieses Viertels",
        descriptionEs: "Los orígenes y la evolución histórica de este barrio",
        icon: "book-open",
      },
      {
        id: "cultural",
        name: "Cultural",
        nameNl: "Cultureel",
        nameFr: "Culturel",
        nameDe: "Kulturell",
        nameEs: "Cultural",
        description: "Art, food, lifestyle, and cultural significance",
        descriptionNl: "Kunst, eten, levensstijl en culturele betekenis",
        descriptionFr: "Art, gastronomie, mode de vie et importance culturelle",
        descriptionDe: "Kunst, Essen, Lebensstil und kulturelle Bedeutung",
        descriptionEs: "Arte, gastronomía, estilo de vida e importancia cultural",
        icon: "coffee",
      },
      {
        id: "modern-times",
        name: "Modern Times",
        nameNl: "Moderne Tijd",
        nameFr: "Époque moderne",
        nameDe: "Moderne Zeit",
        nameEs: "Tiempos modernos",
        description: "What the neighborhood looks like today and how it has evolved",
        descriptionNl: "Hoe de buurt er vandaag uitziet en hoe deze is geëvolueerd",
        descriptionFr: "À quoi ressemble le quartier aujourd'hui et comment il a évolué",
        descriptionDe: "Wie das Viertel heute aussieht und wie es sich entwickelt hat",
        descriptionEs: "Cómo se ve el barrio hoy y cómo ha evolucionado",
        icon: "trending-up",
      },
      {
        id: "walking-tour",
        name: "Walking Tour",
        nameNl: "Wandeltour",
        nameFr: "Visite à pied",
        nameDe: "Rundgang",
        nameEs: "Paseo guiado",
        description: "A guided walk past the best and most famous places in the area",
        descriptionNl: "Een begeleide wandeling langs de beste en beroemdste plekken in het gebied",
        descriptionFr: "Une promenade guidée devant les meilleurs et les plus célèbres endroits du quartier",
        descriptionDe: "Ein geführter Spaziergang an den besten und berühmtesten Orten der Gegend vorbei",
        descriptionEs: "Un paseo guiado por los mejores y más famosos lugares de la zona",
        icon: "navigation",
      },
    ],
    topics: [
      {
        id: "montmartre",
        name: "Montmartre",
        nameNl: "Montmartre",
        nameFr: "Montmartre",
        nameDe: "Montmartre",
        nameEs: "Montmartre",
        description: "The hilltop village of artists, bohemians, and the Sacré-Cœur",
        descriptionNl: "Het bergdorp van kunstenaars, bohemiens en de Sacré-Cœur",
        descriptionFr: "Le village perché des artistes, des bohèmes et du Sacré-Cœur",
        descriptionDe: "Das Hügeldorf der Künstler, Bohemiens und des Sacré-Cœur",
        descriptionEs: "El pueblo en la colina de artistas, bohemios y el Sacré-Cœur",
      },
      {
        id: "montmartre-walk",
        name: "Walking Tour: Secret Montmartre",
        nameNl: "Wandeltour: Geheim Montmartre",
        nameFr: "Visite à pied : Montmartre secret",
        nameDe: "Rundgang: Das geheime Montmartre",
        nameEs: "Paseo guiado: Montmartre secreto",
        description: "Hidden vineyards, quiet passages, and the streets Renoir and Van Gogh once walked",
        descriptionNl: "Verborgen wijngaarden, stille doorgangen en de straten waar Renoir en Van Gogh ooit liepen",
        descriptionFr: "Vignobles cachés, passages tranquilles et les rues que Renoir et Van Gogh ont arpentées",
        descriptionDe: "Versteckte Weinberge, stille Passagen und die Straßen, auf denen Renoir und Van Gogh einst gingen",
        descriptionEs: "Viñedos escondidos, pasajes tranquilos y las calles que Renoir y Van Gogh recorrieron",
      },
      {
        id: "le-marais",
        name: "Le Marais",
        nameNl: "Le Marais",
        nameFr: "Le Marais",
        nameDe: "Le Marais",
        nameEs: "Le Marais",
        description: "Medieval streets, Jewish heritage, and trendy boutiques",
        descriptionNl: "Middeleeuwse straten, Joods erfgoed en trendy boetieks",
        descriptionFr: "Rues médiévales, patrimoine juif et boutiques tendance",
        descriptionDe: "Mittelalterliche Straßen, jüdisches Erbe und trendige Boutiquen",
        descriptionEs: "Calles medievales, herencia judía y boutiques de moda",
      },
      {
        id: "pigalle",
        name: "Pigalle",
        nameNl: "Pigalle",
        nameFr: "Pigalle",
        nameDe: "Pigalle",
        nameEs: "Pigalle",
        description: "From the Moulin Rouge to SoPi: the neighborhood that never stops reinventing itself",
        descriptionNl: "Van de Moulin Rouge tot SoPi: de buurt die zichzelf nooit stopt met heruitvinden",
        descriptionFr: "Du Moulin Rouge à SoPi : le quartier qui ne cesse de se réinventer",
        descriptionDe: "Vom Moulin Rouge bis SoPi: das Viertel, das sich immer wieder neu erfindet",
        descriptionEs: "Desde el Moulin Rouge hasta SoPi: el barrio que nunca deja de reinventarse",
      },
      {
        id: "saint-germain",
        name: "Saint-Germain-des-Prés",
        nameNl: "Saint-Germain-des-Prés",
        nameFr: "Saint-Germain-des-Prés",
        nameDe: "Saint-Germain-des-Prés",
        nameEs: "Saint-Germain-des-Prés",
        description: "The intellectual heart of Paris and its legendary cafés",
        descriptionNl: "Het intellectuele hart van Parijs en zijn legendarische cafés",
        descriptionFr: "Le cœur intellectuel de Paris et ses cafés légendaires",
        descriptionDe: "Das intellektuelle Herz von Paris und seine legendären Cafés",
        descriptionEs: "El corazón intelectual de París y sus cafés legendarios",
      },
      {
        id: "latin-quarter",
        name: "Latin Quarter",
        nameNl: "Quartier Latin",
        nameFr: "Quartier Latin",
        nameDe: "Quartier Latin",
        nameEs: "Barrio Latino",
        description: "The student district with centuries of academic tradition",
        descriptionNl: "De studentenwijk met eeuwen academische traditie",
        descriptionFr: "Le quartier étudiant avec des siècles de tradition académique",
        descriptionDe: "Das Studentenviertel mit jahrhundertelanger akademischer Tradition",
        descriptionEs: "El barrio estudiantil con siglos de tradición académica",
      },
      {
        id: "belleville",
        name: "Belleville",
        nameNl: "Belleville",
        nameFr: "Belleville",
        nameDe: "Belleville",
        nameEs: "Belleville",
        description: "The multicultural melting pot where Edith Piaf was born",
        descriptionNl: "De multiculturele smeltkroes waar Edith Piaf werd geboren",
        descriptionFr: "Le creuset multiculturel où est née Édith Piaf",
        descriptionDe: "Der multikulturelle Schmelztiegel, in dem Édith Piaf geboren wurde",
        descriptionEs: "El crisol multicultural donde nació Édith Piaf",
      },
      {
        id: "ile-de-la-cite",
        name: "Île de la Cité",
        nameNl: "Île de la Cité",
        nameFr: "Île de la Cité",
        nameDe: "Île de la Cité",
        nameEs: "Île de la Cité",
        description: "The island birthplace of Paris with Notre-Dame and the Sainte-Chapelle",
        descriptionNl: "Het eiland waar Parijs geboren werd, met Notre-Dame en de Sainte-Chapelle",
        descriptionFr: "L'île berceau de Paris avec Notre-Dame et la Sainte-Chapelle",
        descriptionDe: "Die Insel, Geburtsort von Paris, mit Notre-Dame und der Sainte-Chapelle",
        descriptionEs: "La isla cuna de París con Notre-Dame y la Sainte-Chapelle",
      },
    ],
  },
  {
    id: "food-drinks",
    name: "Culinary",
    nameNl: "Culinair",
    nameFr: "Gastronomie",
    nameDe: "Kulinarisch",
    nameEs: "Gastronomía",
    icon: "restaurant",
    iconFamily: "MaterialIcons",
    iconImage: require("@/assets/images/category-culinary.png"),
    color: "#E67E22",
    topics: [
      {
        id: "parisian-bistro",
        name: "The Parisian Bistro",
        nameNl: "Het Parijse Bistro",
        nameFr: "Le Bistro parisien",
        nameDe: "Das Pariser Bistro",
        nameEs: "El Bistró parisino",
        description: "The history and soul of the classic neighborhood bistro",
        descriptionNl: "De geschiedenis en ziel van het klassieke buurtbistro",
        descriptionFr: "L'histoire et l'âme du bistro de quartier classique",
        descriptionDe: "Die Geschichte und Seele des klassischen Nachbarschaftsbistros",
        descriptionEs: "La historia y el alma del clásico bistró de barrio",
      },
      {
        id: "rue-montorgueil-walk",
        name: "Walking Tour: Rue Montorgueil",
        nameNl: "Wandeltour: Rue Montorgueil",
        nameFr: "Visite à pied : Rue Montorgueil",
        nameDe: "Rundgang: Rue Montorgueil",
        nameEs: "Paseo guiado: Rue Montorgueil",
        description: "Past the best fromageries, bakeries, and market stalls of this iconic food street",
        descriptionNl: "Langs de beste kaasboeren, bakkers en marktkraampjes van deze iconische foodstraat",
        descriptionFr: "Devant les meilleures fromageries, boulangeries et étals de marché de cette rue gastronomique iconique",
        descriptionDe: "Vorbei an den besten Käseläden, Bäckereien und Marktständen dieser ikonischen Food-Straße",
        descriptionEs: "Pasando por las mejores queserías, panaderías y puestos del mercado de esta icónica calle gastronómica",
      },
      {
        id: "patisserie",
        name: "French Pastry & Pâtisserie",
        nameNl: "Frans Gebak & Patisserie",
        nameFr: "Pâtisserie française",
        nameDe: "Französisches Gebäck & Pâtisserie",
        nameEs: "Pastelería francesa",
        description: "From croissants to macarons: the art and craft of French pastry",
        descriptionNl: "Van croissants tot macarons: de kunst en het vakmanschap van Frans gebak",
        descriptionFr: "Des croissants aux macarons : l'art et le savoir-faire de la pâtisserie française",
        descriptionDe: "Von Croissants bis Macarons: die Kunst und das Handwerk der französischen Pâtisserie",
        descriptionEs: "De croissants a macarons: el arte y la artesanía de la pastelería francesa",
      },
      {
        id: "wine-bars",
        name: "Wine Bars of Paris",
        nameNl: "Wijnbars van Parijs",
        nameFr: "Les Bars à vins de Paris",
        nameDe: "Weinbars von Paris",
        nameEs: "Bares de vino de París",
        description: "The rise of the natural wine bar and Parisian wine culture",
        descriptionNl: "De opkomst van de natuurlijke wijnbar en de Parijse wijncultuur",
        descriptionFr: "L'essor du bar à vins naturels et la culture vinicole parisienne",
        descriptionDe: "Der Aufstieg der Naturweinbar und die Pariser Weinkultur",
        descriptionEs: "El auge del bar de vinos naturales y la cultura vinícola parisina",
      },
      {
        id: "les-halles",
        name: "Les Halles: The Belly of Paris",
        nameNl: "Les Halles: De Buik van Parijs",
        nameFr: "Les Halles : Le Ventre de Paris",
        nameDe: "Les Halles: Der Bauch von Paris",
        nameEs: "Les Halles: El Vientre de París",
        description: "The legendary market hall that Zola called the belly of Paris",
        descriptionNl: "De legendarische markthal die Zola de buik van Parijs noemde",
        descriptionFr: "La légendaire halle de marché que Zola appelait le ventre de Paris",
        descriptionDe: "Die legendäre Markthalle, die Zola den Bauch von Paris nannte",
        descriptionEs: "El legendario mercado que Zola llamó el vientre de París",
      },
      {
        id: "cafe-culture",
        name: "Café Culture",
        nameNl: "Cafécultuur",
        nameFr: "La Culture du café",
        nameDe: "Cafékultur",
        nameEs: "Cultura de café",
        description: "How the Parisian café shaped French philosophy, art, and revolution",
        descriptionNl: "Hoe het Parijse café de Franse filosofie, kunst en revolutie vormde",
        descriptionFr: "Comment le café parisien a façonné la philosophie, l'art et la révolution française",
        descriptionDe: "Wie das Pariser Café die französische Philosophie, Kunst und Revolution prägte",
        descriptionEs: "Cómo el café parisino moldeó la filosofía, el arte y la revolución francesa",
      },
      {
        id: "julia-child",
        name: "Julia Child's Paris",
        nameNl: "Het Parijs van Julia Child",
        nameFr: "Le Paris de Julia Child",
        nameDe: "Julia Childs Paris",
        nameEs: "El París de Julia Child",
        description: "The American chef who brought French cuisine to the world",
        descriptionNl: "De Amerikaanse kok die de Franse keuken naar de wereld bracht",
        descriptionFr: "La cheffe américaine qui a fait connaître la cuisine française au monde entier",
        descriptionDe: "Die amerikanische Köchin, die die französische Küche in die Welt brachte",
        descriptionEs: "La chef estadounidense que llevó la cocina francesa al mundo",
      },
      {
        id: "street-food-markets",
        name: "Street Food & Markets",
        nameNl: "Straateten & Markten",
        nameFr: "Street food & Marchés",
        nameDe: "Straßenessen & Märkte",
        nameEs: "Comida callejera y mercados",
        description: "From crêpes to falafel: the best street markets and their hidden gems",
        descriptionNl: "Van crêpes tot falafel: de beste straatmarkten en hun verborgen parels",
        descriptionFr: "Des crêpes aux falafels : les meilleurs marchés de rue et leurs trésors cachés",
        descriptionDe: "Von Crêpes bis Falafel: die besten Straßenmärkte und ihre verborgenen Schätze",
        descriptionEs: "De crêpes a falafel: los mejores mercados callejeros y sus joyas ocultas",
      },
    ],
  },
];

const amsterdamThemes: Theme[] = [
  {
    id: "history",
    name: "History",
    nameNl: "Geschiedenis",
    nameFr: "Histoire",
    nameDe: "Geschichte",
    nameEs: "Historia",
    icon: "book",
    iconFamily: "Ionicons",
    iconImage: require("@/assets/images/category-history.png"),
    color: "#6B4226",
    topics: [
      {
        id: "ams-founding",
        name: "Amstelredamme: The Birth of Amsterdam",
        nameNl: "Amstelredamme: De Geboorte van Amsterdam",
        nameFr: "Amstelredamme : La Naissance d'Amsterdam",
        nameDe: "Amstelredamme: Die Geburt von Amsterdam",
        nameEs: "Amstelredamme: El Nacimiento de Ámsterdam",
        description: "From fishing village on the Amstel to powerful trading city",
        descriptionNl: "Van vissersdorp aan de Amstel tot machtige handelsstad",
        descriptionFr: "D'un village de pêcheurs sur l'Amstel à une puissante ville commerçante",
        descriptionDe: "Vom Fischerdorf an der Amstel zur mächtigen Handelsstadt",
        descriptionEs: "De pueblo pesquero en el Amstel a poderosa ciudad comercial",
      },
      {
        id: "ams-voc",
        name: "The VOC: The First Multinational",
        nameNl: "De VOC: De Eerste Multinational",
        nameFr: "La VOC : La Première Multinationale",
        nameDe: "Die VOC: Das erste multinationale Unternehmen",
        nameEs: "La VOC: La Primera Multinacional",
        description: "The Dutch East India Company and its global empire",
        descriptionNl: "De Vereenigde Oost-Indische Compagnie en haar wereldrijk",
        descriptionFr: "La Compagnie néerlandaise des Indes orientales et son empire mondial",
        descriptionDe: "Die Niederländische Ostindien-Kompanie und ihr Weltreich",
        descriptionEs: "La Compañía Neerlandesa de las Indias Orientales y su imperio global",
      },
      {
        id: "ams-slave-trade",
        name: "Amsterdam and the Slave Trade",
        nameNl: "Amsterdam en de Slavenhandel",
        nameFr: "Amsterdam et la Traite des Esclaves",
        nameDe: "Amsterdam und der Sklavenhandel",
        nameEs: "Ámsterdam y la Trata de Esclavos",
        description: "The dark side of Amsterdam's trading history",
        descriptionNl: "De duistere kant van de Amsterdamse handelsgeschiedenis",
        descriptionFr: "Le côté sombre de l'histoire commerciale d'Amsterdam",
        descriptionDe: "Die dunkle Seite der Amsterdamer Handelsgeschichte",
        descriptionEs: "El lado oscuro de la historia comercial de Ámsterdam",
      },
      {
        id: "ams-alteratie",
        name: "The Alteratie of 1578",
        nameNl: "De Alteratie van 1578",
        nameFr: "L'Altération de 1578",
        nameDe: "Die Alteratie von 1578",
        nameEs: "La Alteración de 1578",
        description: "How Amsterdam became Protestant and changed the course of the city",
        descriptionNl: "Hoe Amsterdam protestant werd en de koers van de stad veranderde",
        descriptionFr: "Comment Amsterdam est devenue protestante et a changé le cours de la ville",
        descriptionDe: "Wie Amsterdam protestantisch wurde und den Kurs der Stadt veränderte",
        descriptionEs: "Cómo Ámsterdam se hizo protestante y cambió el rumbo de la ciudad",
      },
      {
        id: "ams-great-fire",
        name: "The Great City Fire of 1421",
        nameNl: "De Grote Stadsbrand van 1421",
        nameFr: "Le Grand Incendie de 1421",
        nameDe: "Der Große Stadtbrand von 1421",
        nameEs: "El Gran Incendio de 1421",
        description: "The fire that destroyed medieval Amsterdam",
        descriptionNl: "Het vuur dat het middeleeuwse Amsterdam verwoestte",
        descriptionFr: "L'incendie qui a détruit l'Amsterdam médiéval",
        descriptionDe: "Das Feuer, das das mittelalterliche Amsterdam zerstörte",
        descriptionEs: "El fuego que destruyó la Ámsterdam medieval",
      },
      {
        id: "ams-napoleon",
        name: "Napoleon and Amsterdam",
        nameNl: "Napoleon en Amsterdam",
        nameFr: "Napoléon et Amsterdam",
        nameDe: "Napoleon und Amsterdam",
        nameEs: "Napoleón y Ámsterdam",
        description: "When Amsterdam became capital of the Kingdom of Holland",
        descriptionNl: "Toen Amsterdam hoofdstad van het Koninkrijk Holland werd",
        descriptionFr: "Quand Amsterdam est devenue la capitale du Royaume de Hollande",
        descriptionDe: "Als Amsterdam Hauptstadt des Königreichs Holland wurde",
        descriptionEs: "Cuando Ámsterdam se convirtió en la capital del Reino de Holanda",
      },
      {
        id: "ams-watergeuzen",
        name: "The Watergeuzen",
        nameNl: "De Watergeuzen",
        nameFr: "Les Gueux de Mer",
        nameDe: "Die Wassergeusen",
        nameEs: "Los Mendigos del Mar",
        description: "The rebels who freed Amsterdam from Spain",
        descriptionNl: "De opstandelingen die Amsterdam bevrijdden van Spanje",
        descriptionFr: "Les rebelles qui ont libéré Amsterdam de l'Espagne",
        descriptionDe: "Die Rebellen, die Amsterdam von Spanien befreiten",
        descriptionEs: "Los rebeldes que liberaron Ámsterdam de España",
      },
      {
        id: "ams-anjer-1945",
        name: "The Carnation Revolution of 1945",
        nameNl: "De Anjerrevolutie van 1945",
        nameFr: "La Révolution des Œillets de 1945",
        nameDe: "Die Nelkenrevolution von 1945",
        nameEs: "La Revolución de los Claveles de 1945",
        description: "Silent resistance and liberation of Amsterdam",
        descriptionNl: "Stil verzet en de bevrijding van Amsterdam",
        descriptionFr: "Résistance silencieuse et libération d'Amsterdam",
        descriptionDe: "Stiller Widerstand und Befreiung von Amsterdam",
        descriptionEs: "Resistencia silenciosa y liberación de Ámsterdam",
      },
    ],
  },
  {
    id: "golden-age",
    name: "The Golden Age",
    nameNl: "De Gouden Eeuw",
    nameFr: "L'Âge d'Or",
    nameDe: "Das Goldene Zeitalter",
    nameEs: "La Edad de Oro",
    icon: "sunny",
    iconFamily: "Ionicons",
    iconImage: require("@/assets/images/category-history.png"),
    color: "#DAA520",
    angles: [
      {
        id: "historical",
        name: "Historical",
        nameNl: "Historisch",
        nameFr: "Historique",
        nameDe: "Historisch",
        nameEs: "Histórico",
        description: "Facts, dates, and chronological storytelling",
        descriptionNl: "Feiten, data en chronologisch vertellen",
        descriptionFr: "Faits, dates et récit chronologique",
        descriptionDe: "Fakten, Daten und chronologisches Erzählen",
        descriptionEs: "Hechos, fechas y narración cronológica",
        icon: "book-open",
      },
      {
        id: "personal-stories",
        name: "Personal Stories",
        nameNl: "Persoonlijke Verhalen",
        nameFr: "Histoires personnelles",
        nameDe: "Persönliche Geschichten",
        nameEs: "Historias personales",
        description: "The story told from the iconic figures involved",
        descriptionNl: "Het verhaal verteld vanuit de iconische figuren die erbij betrokken waren",
        descriptionFr: "L'histoire racontée du point de vue des personnages emblématiques",
        descriptionDe: "Die Geschichte aus der Perspektive der beteiligten ikonischen Figuren",
        descriptionEs: "La historia contada desde las figuras icónicas involucradas",
        icon: "users",
      },
    ],
    topics: [
      {
        id: "ams-rembrandt",
        name: "Rembrandt: Master of Light",
        nameNl: "Rembrandt: Meester van het Licht",
        nameFr: "Rembrandt : Maître de la Lumière",
        nameDe: "Rembrandt: Meister des Lichts",
        nameEs: "Rembrandt: Maestro de la Luz",
        description: "His life, work, and downfall in Amsterdam",
        descriptionNl: "Zijn leven, werk en ondergang in Amsterdam",
        descriptionFr: "Sa vie, son œuvre et sa chute à Amsterdam",
        descriptionDe: "Sein Leben, Werk und Untergang in Amsterdam",
        descriptionEs: "Su vida, obra y caída en Ámsterdam",
      },
      {
        id: "ams-rembrandt-walk",
        name: "Walking Tour: Rembrandtplein & the Night Watch",
        nameNl: "Wandeltour: Rembrandtplein & de Nachtwacht",
        nameFr: "Visite à pied : Rembrandtplein et la Ronde de Nuit",
        nameDe: "Rundgang: Rembrandtplein & die Nachtwache",
        nameEs: "Paseo guiado: Rembrandtplein y la Ronda de Noche",
        description: "Walk through Rembrandt's Amsterdam",
        descriptionNl: "Loop door Rembrandts Amsterdam",
        descriptionFr: "Marchez dans l'Amsterdam de Rembrandt",
        descriptionDe: "Wandeln Sie durch Rembrandts Amsterdam",
        descriptionEs: "Camina por el Ámsterdam de Rembrandt",
      },
      {
        id: "ams-canal-ring",
        name: "The Canal Ring: Built on Piles",
        nameNl: "De Grachtengordel: Gebouwd op Palen",
        nameFr: "La Ceinture de Canaux : Bâtie sur Pilotis",
        nameDe: "Der Grachtengürtel: Auf Pfählen erbaut",
        nameEs: "El Cinturón de Canales: Construido sobre Pilotes",
        description: "How Amsterdam built its iconic canals",
        descriptionNl: "Hoe Amsterdam zijn iconische grachten aanlegde",
        descriptionFr: "Comment Amsterdam a construit ses canaux emblématiques",
        descriptionDe: "Wie Amsterdam seine ikonischen Grachten anlegte",
        descriptionEs: "Cómo Ámsterdam construyó sus icónicos canales",
      },
      {
        id: "ams-tulipmania",
        name: "Tulipmania: The First Stock Market Bubble",
        nameNl: "Tulpenmanie: De Eerste Beursbubbel",
        nameFr: "La Tulipomanie : La Première Bulle Boursière",
        nameDe: "Tulpenmanie: Die erste Börsenblase",
        nameEs: "Tulipomanía: La Primera Burbuja Bursátil",
        description: "When tulip bulbs were worth more than houses",
        descriptionNl: "Toen tulpenbollen meer waard waren dan huizen",
        descriptionFr: "Quand les bulbes de tulipes valaient plus que des maisons",
        descriptionDe: "Als Tulpenzwiebeln mehr wert waren als Häuser",
        descriptionEs: "Cuando los bulbos de tulipán valían más que las casas",
      },
      {
        id: "ams-spinoza",
        name: "Spinoza in Amsterdam",
        nameNl: "Spinoza in Amsterdam",
        nameFr: "Spinoza à Amsterdam",
        nameDe: "Spinoza in Amsterdam",
        nameEs: "Spinoza en Ámsterdam",
        description: "The philosopher who changed the world from the Jewish Quarter",
        descriptionNl: "De filosoof die in de Jodenbuurt de wereld veranderde",
        descriptionFr: "Le philosophe qui a changé le monde depuis le quartier juif",
        descriptionDe: "Der Philosoph, der die Welt vom Jüdischen Viertel aus veränderte",
        descriptionEs: "El filósofo que cambió el mundo desde el barrio judío",
      },
      {
        id: "ams-jordaan-golden-age",
        name: "Walking Tour: The Jordaan in the Golden Age",
        nameNl: "Wandeltour: De Jordaan in de Gouden Eeuw",
        nameFr: "Visite à pied : Le Jordaan à l'Âge d'Or",
        nameDe: "Rundgang: Die Jordaan im Goldenen Zeitalter",
        nameEs: "Paseo guiado: El Jordaan en la Edad de Oro",
        description: "Working-class neighborhood full of stories",
        descriptionNl: "Arbeidersbuurt vol verhalen",
        descriptionFr: "Quartier ouvrier plein d'histoires",
        descriptionDe: "Arbeiterviertel voller Geschichten",
        descriptionEs: "Barrio obrero lleno de historias",
      },
      {
        id: "ams-east-india-house",
        name: "The East India House",
        nameNl: "Het Oost-Indisch Huis",
        nameFr: "La Maison des Indes Orientales",
        nameDe: "Das Ostindienhaus",
        nameEs: "La Casa de las Indias Orientales",
        description: "Where the VOC governed its global empire",
        descriptionNl: "Waar de VOC haar wereldrijk bestuurde",
        descriptionFr: "Où la VOC gouvernait son empire mondial",
        descriptionDe: "Wo die VOC ihr Weltreich regierte",
        descriptionEs: "Donde la VOC gobernaba su imperio global",
      },
      {
        id: "ams-free-haven",
        name: "Haven of Free Thought",
        nameNl: "Vrijhaven der Gedachten",
        nameFr: "Havre de Libre Pensée",
        nameDe: "Freihafen des Denkens",
        nameEs: "Refugio del Libre Pensamiento",
        description: "How Amsterdam became the center of free thinking and the printing press",
        descriptionNl: "Hoe Amsterdam het centrum van vrij denken en de drukpers werd",
        descriptionFr: "Comment Amsterdam est devenue le centre de la libre pensée et de l'imprimerie",
        descriptionDe: "Wie Amsterdam zum Zentrum des freien Denkens und der Druckerpresse wurde",
        descriptionEs: "Cómo Ámsterdam se convirtió en el centro del libre pensamiento y la imprenta",
      },
    ],
  },
  {
    id: "museums",
    name: "Museums",
    nameNl: "Musea",
    nameFr: "Musées",
    nameDe: "Museen",
    nameEs: "Museos",
    icon: "museum",
    iconFamily: "MaterialIcons",
    iconImage: require("@/assets/images/category-museums.png"),
    color: "#2980B9",
    angles: [
      {
        id: "origin",
        name: "Origin of the Museum",
        nameNl: "Ontstaan van het Museum",
        nameFr: "Origine du Musée",
        nameDe: "Ursprung des Museums",
        nameEs: "Origen del Museo",
        description: "The founding story and how the museum came to be",
        descriptionNl: "Het ontstaansverhaal en hoe het museum tot stand kwam",
        descriptionFr: "L'histoire de sa fondation et comment le musée est né",
        descriptionDe: "Die Gründungsgeschichte und wie das Museum entstand",
        descriptionEs: "La historia de su fundación y cómo nació el museo",
        icon: "clock",
      },
      {
        id: "prominent-art",
        name: "Prominent Art Pieces",
        nameNl: "Prominente Kunstwerken",
        nameFr: "Œuvres d'art emblématiques",
        nameDe: "Bedeutende Kunstwerke",
        nameEs: "Obras de arte destacadas",
        description: "The most famous and significant works in the collection",
        descriptionNl: "De beroemdste en belangrijkste werken in de collectie",
        descriptionFr: "Les œuvres les plus célèbres et les plus importantes de la collection",
        descriptionDe: "Die berühmtesten und bedeutendsten Werke der Sammlung",
        descriptionEs: "Las obras más famosas e importantes de la colección",
        icon: "image",
      },
      {
        id: "architecture",
        name: "Architecture & Building",
        nameNl: "Architectuur & Gebouw",
        nameFr: "Architecture & Bâtiment",
        nameDe: "Architektur & Gebäude",
        nameEs: "Arquitectura & Edificio",
        description: "The architectural story and design of the building itself",
        descriptionNl: "Het architectuurverhaal en het ontwerp van het gebouw zelf",
        descriptionFr: "L'histoire architecturale et le design du bâtiment lui-même",
        descriptionDe: "Die architektonische Geschichte und Gestaltung des Gebäudes selbst",
        descriptionEs: "La historia arquitectónica y el diseño del edificio en sí",
        icon: "home",
      },
    ],
    topics: [
      {
        id: "ams-rijksmuseum",
        name: "The Rijksmuseum",
        nameNl: "Het Rijksmuseum",
        nameFr: "Le Rijksmuseum",
        nameDe: "Das Rijksmuseum",
        nameEs: "El Rijksmuseum",
        description: "The Netherlands' greatest art treasure and the story behind it",
        descriptionNl: "Nederlands grootste kunstschat en het verhaal erachter",
        descriptionFr: "Le plus grand trésor artistique des Pays-Bas et son histoire",
        descriptionDe: "Der größte Kunstschatz der Niederlande und die Geschichte dahinter",
        descriptionEs: "El mayor tesoro artístico de los Países Bajos y su historia",
      },
      {
        id: "ams-van-gogh",
        name: "Van Gogh Museum",
        nameNl: "Van Gogh Museum",
        nameFr: "Musée Van Gogh",
        nameDe: "Van Gogh Museum",
        nameEs: "Museo Van Gogh",
        description: "The life and suffering of Vincent, told through his work",
        descriptionNl: "Het leven en lijden van Vincent, verteld door zijn werk",
        descriptionFr: "La vie et la souffrance de Vincent, racontées à travers son œuvre",
        descriptionDe: "Das Leben und Leiden von Vincent, erzählt durch sein Werk",
        descriptionEs: "La vida y el sufrimiento de Vincent, contados a través de su obra",
      },
      {
        id: "ams-stedelijk",
        name: "Stedelijk Museum",
        nameNl: "Stedelijk Museum",
        nameFr: "Musée Stedelijk",
        nameDe: "Stedelijk Museum",
        nameEs: "Museo Stedelijk",
        description: "Modern and contemporary art in the heart of Amsterdam",
        descriptionNl: "Moderne en hedendaagse kunst in het hart van Amsterdam",
        descriptionFr: "Art moderne et contemporain au cœur d'Amsterdam",
        descriptionDe: "Moderne und zeitgenössische Kunst im Herzen von Amsterdam",
        descriptionEs: "Arte moderno y contemporáneo en el corazón de Ámsterdam",
      },
      {
        id: "ams-anne-frank",
        name: "Anne Frank House",
        nameNl: "Anne Frank Huis",
        nameFr: "Maison d'Anne Frank",
        nameDe: "Anne-Frank-Haus",
        nameEs: "Casa de Ana Frank",
        description: "The secret annex and the diary that changed the world",
        descriptionNl: "Het achterhuis en het dagboek dat de wereld veranderde",
        descriptionFr: "L'annexe secrète et le journal qui a changé le monde",
        descriptionDe: "Das Hinterhaus und das Tagebuch, das die Welt veränderte",
        descriptionEs: "El anexo secreto y el diario que cambió el mundo",
      },
      {
        id: "ams-scheepvaart",
        name: "The Maritime Museum",
        nameNl: "Het Scheepvaartmuseum",
        nameFr: "Le Musée Maritime",
        nameDe: "Das Schifffahrtsmuseum",
        nameEs: "El Museo Marítimo",
        description: "The maritime glory of Amsterdam",
        descriptionNl: "De maritieme glorie van Amsterdam",
        descriptionFr: "La gloire maritime d'Amsterdam",
        descriptionDe: "Die maritime Glorie von Amsterdam",
        descriptionEs: "La gloria marítima de Ámsterdam",
      },
      {
        id: "ams-hermitage",
        name: "Hermitage Amsterdam",
        nameNl: "Hermitage Amsterdam",
        nameFr: "Hermitage Amsterdam",
        nameDe: "Hermitage Amsterdam",
        nameEs: "Hermitage Ámsterdam",
        description: "Russian art on the Amstel river",
        descriptionNl: "Russische kunst aan de Amstel",
        descriptionFr: "L'art russe sur l'Amstel",
        descriptionDe: "Russische Kunst an der Amstel",
        descriptionEs: "Arte ruso en el río Amstel",
      },
      {
        id: "ams-nemo",
        name: "NEMO Science Museum",
        nameNl: "NEMO Science Museum",
        nameFr: "NEMO Musée des Sciences",
        nameDe: "NEMO Wissenschaftsmuseum",
        nameEs: "NEMO Museo de Ciencias",
        description: "Renzo Piano's green ship full of science",
        descriptionNl: "Renzo Piano's groene schip vol wetenschap",
        descriptionFr: "Le navire vert de Renzo Piano plein de science",
        descriptionDe: "Renzo Pianos grünes Schiff voller Wissenschaft",
        descriptionEs: "El barco verde de Renzo Piano lleno de ciencia",
      },
      {
        id: "ams-rembrandthuis",
        name: "Museum het Rembrandthuis",
        nameNl: "Museum het Rembrandthuis",
        nameFr: "Musée de la Maison de Rembrandt",
        nameDe: "Museum Rembrandthaus",
        nameEs: "Museo Casa de Rembrandt",
        description: "Where the master lived and worked",
        descriptionNl: "Waar de meester woonde en werkte",
        descriptionFr: "Où le maître vivait et travaillait",
        descriptionDe: "Wo der Meister lebte und arbeitete",
        descriptionEs: "Donde el maestro vivió y trabajó",
      },
    ],
  },
  {
    id: "epic-buildings",
    name: "Buildings & Monuments",
    nameNl: "Gebouwen & Monumenten",
    nameFr: "Bâtiments & Monuments",
    nameDe: "Gebäude & Denkmäler",
    nameEs: "Edificios y Monumentos",
    icon: "business",
    iconFamily: "Ionicons",
    iconImage: require("@/assets/images/category-epic-buildings.png"),
    color: "#7A8B9A",
    topics: [
      {
        id: "ams-royal-palace",
        name: "The Royal Palace",
        nameNl: "Het Koninklijk Paleis",
        nameFr: "Le Palais Royal",
        nameDe: "Der Königliche Palast",
        nameEs: "El Palacio Real",
        description: "From city hall to royal palace on Dam Square",
        descriptionNl: "Van stadhuis tot koninklijk paleis op de Dam",
        descriptionFr: "De l'hôtel de ville au palais royal sur la place du Dam",
        descriptionDe: "Vom Rathaus zum Königspalast am Dam-Platz",
        descriptionEs: "De ayuntamiento a palacio real en la Plaza Dam",
      },
      {
        id: "ams-westerkerk",
        name: "The Westerkerk",
        nameNl: "De Westerkerk",
        nameFr: "L'Église de l'Ouest",
        nameDe: "Die Westerkerk",
        nameEs: "La Westerkerk",
        description: "Rembrandt's final resting place and the heart of the Jordaan",
        descriptionNl: "Rembrandts laatste rustplaats en het hart van de Jordaan",
        descriptionFr: "La dernière demeure de Rembrandt et le cœur du Jordaan",
        descriptionDe: "Rembrandts letzte Ruhestätte und das Herz der Jordaan",
        descriptionEs: "El lugar de descanso final de Rembrandt y el corazón del Jordaan",
      },
      {
        id: "ams-centraal-station",
        name: "Centraal Station",
        nameNl: "Centraal Station",
        nameFr: "La Gare Centrale",
        nameDe: "Der Hauptbahnhof",
        nameEs: "La Estación Central",
        description: "The station that separated the city from the water",
        descriptionNl: "Het station dat de stad van het water scheidde",
        descriptionFr: "La gare qui a séparé la ville de l'eau",
        descriptionDe: "Der Bahnhof, der die Stadt vom Wasser trennte",
        descriptionEs: "La estación que separó la ciudad del agua",
      },
      {
        id: "ams-oude-kerk",
        name: "The Oude Kerk",
        nameNl: "De Oude Kerk",
        nameFr: "La Vieille Église",
        nameDe: "Die Alte Kirche",
        nameEs: "La Iglesia Vieja",
        description: "Amsterdam's oldest building in the heart of the Red Light District",
        descriptionNl: "Amsterdams oudste gebouw in het hart van de Wallen",
        descriptionFr: "Le plus ancien bâtiment d'Amsterdam au cœur du quartier rouge",
        descriptionDe: "Amsterdams ältestes Gebäude im Herzen des Rotlichtviertels",
        descriptionEs: "El edificio más antiguo de Ámsterdam en el corazón del barrio rojo",
      },
      {
        id: "ams-scheepvaarthuis",
        name: "Het Scheepvaarthuis",
        nameNl: "Het Scheepvaarthuis",
        nameFr: "La Maison de la Navigation",
        nameDe: "Das Scheepvaarthuis",
        nameEs: "La Casa de la Navegación",
        description: "The most beautiful office building in the Netherlands, Amsterdam School style",
        descriptionNl: "Het mooiste kantoorgebouw van Nederland in Amsterdamse Schoolstijl",
        descriptionFr: "Le plus beau bâtiment de bureaux des Pays-Bas, style École d'Amsterdam",
        descriptionDe: "Das schönste Bürogebäude der Niederlande im Stil der Amsterdamer Schule",
        descriptionEs: "El edificio de oficinas más bonito de los Países Bajos, estilo Escuela de Ámsterdam",
      },
      {
        id: "ams-magere-brug",
        name: "The Magere Brug",
        nameNl: "De Magere Brug",
        nameFr: "Le Pont Maigre",
        nameDe: "Die Magere Brücke",
        nameEs: "El Puente Magere",
        description: "The most famous bridge of Amsterdam",
        descriptionNl: "De beroemdste brug van Amsterdam",
        descriptionFr: "Le pont le plus célèbre d'Amsterdam",
        descriptionDe: "Die berühmteste Brücke von Amsterdam",
        descriptionEs: "El puente más famoso de Ámsterdam",
      },
      {
        id: "ams-tuschinski",
        name: "Tuschinski Theater",
        nameNl: "Tuschinski Theater",
        nameFr: "Théâtre Tuschinski",
        nameDe: "Tuschinski-Theater",
        nameEs: "Teatro Tuschinski",
        description: "Art deco gem and the most beautiful cinema palace in the world",
        descriptionNl: "Art deco-parel en het mooiste filmpaleis ter wereld",
        descriptionFr: "Joyau art déco et le plus beau palais du cinéma au monde",
        descriptionDe: "Art-Déco-Juwel und der schönste Filmpalast der Welt",
        descriptionEs: "Joya art déco y el palacio de cine más hermoso del mundo",
      },
      {
        id: "ams-eye",
        name: "EYE Film Museum",
        nameNl: "Het EYE Filmmuseum",
        nameFr: "Le Musée du Film EYE",
        nameDe: "Das EYE Filmmuseum",
        nameEs: "El Museo de Cine EYE",
        description: "Futuristic film palace on the IJ river",
        descriptionNl: "Futuristisch filmpaleis aan het IJ",
        descriptionFr: "Palais du cinéma futuriste sur l'IJ",
        descriptionDe: "Futuristischer Filmpalast am IJ",
        descriptionEs: "Palacio de cine futurista en el río IJ",
      },
    ],
  },
  {
    id: "modern-history",
    name: "Modern History",
    nameNl: "Moderne Geschiedenis",
    nameFr: "Histoire moderne",
    nameDe: "Moderne Geschichte",
    nameEs: "Historia moderna",
    icon: "history",
    iconFamily: "MaterialIcons",
    iconImage: require("@/assets/images/category-modern-history.png"),
    color: "#8E44AD",
    topics: [
      {
        id: "ams-wwii",
        name: "Amsterdam in World War II",
        nameNl: "Amsterdam in de Tweede Wereldoorlog",
        nameFr: "Amsterdam pendant la Seconde Guerre mondiale",
        nameDe: "Amsterdam im Zweiten Weltkrieg",
        nameEs: "Ámsterdam en la Segunda Guerra Mundial",
        description: "Occupation, betrayal, and resistance",
        descriptionNl: "Bezetting, verraad en verzet",
        descriptionFr: "Occupation, trahison et résistance",
        descriptionDe: "Besatzung, Verrat und Widerstand",
        descriptionEs: "Ocupación, traición y resistencia",
      },
      {
        id: "ams-february-strike",
        name: "The February Strike of 1941",
        nameNl: "De Februaristaking van 1941",
        nameFr: "La Grève de Février 1941",
        nameDe: "Der Februarstreik von 1941",
        nameEs: "La Huelga de Febrero de 1941",
        description: "A unique protest against the persecution of Jews",
        descriptionNl: "Uniek protest tegen de Jodenvervolging",
        descriptionFr: "Une protestation unique contre la persécution des Juifs",
        descriptionDe: "Ein einzigartiger Protest gegen die Judenverfolgung",
        descriptionEs: "Una protesta única contra la persecución de los judíos",
      },
      {
        id: "ams-jewish-quarter-walk",
        name: "Walking Tour: Jewish Amsterdam",
        nameNl: "Wandeltour: Joods Amsterdam",
        nameFr: "Visite à pied : Amsterdam Juif",
        nameDe: "Rundgang: Jüdisches Amsterdam",
        nameEs: "Paseo guiado: Ámsterdam Judío",
        description: "Walk through the Jewish Quarter and its memories",
        descriptionNl: "Wandel door de Jodenbuurt en haar herinneringen",
        descriptionFr: "Promenez-vous dans le quartier juif et ses souvenirs",
        descriptionDe: "Wandeln Sie durch das Jüdische Viertel und seine Erinnerungen",
        descriptionEs: "Pasea por el barrio judío y sus recuerdos",
      },
      {
        id: "ams-anne-frank-life",
        name: "Anne Frank: The Girl Behind the Diary",
        nameNl: "Anne Frank: Het Meisje Achter het Dagboek",
        nameFr: "Anne Frank : La Fille Derrière le Journal",
        nameDe: "Anne Frank: Das Mädchen hinter dem Tagebuch",
        nameEs: "Ana Frank: La Chica Detrás del Diario",
        description: "Her life in Amsterdam before and during hiding",
        descriptionNl: "Haar leven in Amsterdam voor en tijdens de onderduik",
        descriptionFr: "Sa vie à Amsterdam avant et pendant la clandestinité",
        descriptionDe: "Ihr Leben in Amsterdam vor und während des Untertauchens",
        descriptionEs: "Su vida en Ámsterdam antes y durante la clandestinidad",
      },
      {
        id: "ams-provos",
        name: "The Provos and the 1960s",
        nameNl: "De Provo's en de Jaren '60",
        nameFr: "Les Provos et les Années 60",
        nameDe: "Die Provos und die 1960er Jahre",
        nameEs: "Los Provos y los Años 60",
        description: "Amsterdam's counterculture that inspired the world",
        descriptionNl: "Amsterdamse tegencultuur die de wereld inspireerde",
        descriptionFr: "La contre-culture amsterdamoise qui a inspiré le monde",
        descriptionDe: "Amsterdams Gegenkultur, die die Welt inspirierte",
        descriptionEs: "La contracultura de Ámsterdam que inspiró al mundo",
      },
      {
        id: "ams-squatter-movement",
        name: "The Squatter Movement",
        nameNl: "De Kraakbeweging",
        nameFr: "Le Mouvement Squat",
        nameDe: "Die Hausbesetzerbewegung",
        nameEs: "El Movimiento Okupa",
        description: "How squatters changed the face of Amsterdam",
        descriptionNl: "Hoe krakers het gezicht van Amsterdam veranderden",
        descriptionFr: "Comment les squatteurs ont changé le visage d'Amsterdam",
        descriptionDe: "Wie Hausbesetzer das Gesicht von Amsterdam veränderten",
        descriptionEs: "Cómo los okupas cambiaron la cara de Ámsterdam",
      },
      {
        id: "ams-gay-capital",
        name: "Amsterdam as Gay Capital",
        nameNl: "Amsterdam als Gayhoofdstad",
        nameFr: "Amsterdam, Capitale Gay",
        nameDe: "Amsterdam als Schwulenhauptstadt",
        nameEs: "Ámsterdam como Capital Gay",
        description: "The first same-sex marriage in the world and the fight for equality",
        descriptionNl: "Het eerste homohuwelijk ter wereld en de strijd voor gelijkheid",
        descriptionFr: "Le premier mariage homosexuel au monde et le combat pour l'égalité",
        descriptionDe: "Die erste gleichgeschlechtliche Ehe der Welt und der Kampf für Gleichberechtigung",
        descriptionEs: "El primer matrimonio del mismo sexo en el mundo y la lucha por la igualdad",
      },
      {
        id: "ams-bijlmerramp",
        name: "The Bijlmer Disaster of 1992",
        nameNl: "De Bijlmerramp van 1992",
        nameFr: "La Catastrophe du Bijlmer de 1992",
        nameDe: "Die Bijlmer-Katastrophe von 1992",
        nameEs: "El Desastre del Bijlmer de 1992",
        description: "The plane crash that marked a community forever",
        descriptionNl: "De vliegramp die een gemeenschap voor altijd tekende",
        descriptionFr: "L'accident d'avion qui a marqué une communauté à jamais",
        descriptionDe: "Der Flugzeugabsturz, der eine Gemeinschaft für immer zeichnete",
        descriptionEs: "El accidente aéreo que marcó a una comunidad para siempre",
      },
    ],
  },
  {
    id: "neighborhoods",
    name: "Neighborhoods",
    nameNl: "Wijken",
    nameFr: "Quartiers",
    nameDe: "Stadtviertel",
    nameEs: "Barrios",
    icon: "map",
    iconFamily: "Feather",
    iconImage: require("@/assets/images/category-neighborhoods.png"),
    color: "#27AE60",
    angles: [
      {
        id: "historical",
        name: "Historical",
        nameNl: "Historisch",
        nameFr: "Historique",
        nameDe: "Historisch",
        nameEs: "Histórico",
        description: "The origins and historical evolution of this neighborhood",
        descriptionNl: "De oorsprong en historische ontwikkeling van deze buurt",
        descriptionFr: "Les origines et l'évolution historique de ce quartier",
        descriptionDe: "Die Ursprünge und die historische Entwicklung dieses Viertels",
        descriptionEs: "Los orígenes y la evolución histórica de este barrio",
        icon: "book-open",
      },
      {
        id: "cultural",
        name: "Cultural",
        nameNl: "Cultureel",
        nameFr: "Culturel",
        nameDe: "Kulturell",
        nameEs: "Cultural",
        description: "Art, food, lifestyle, and cultural significance",
        descriptionNl: "Kunst, eten, levensstijl en culturele betekenis",
        descriptionFr: "Art, gastronomie, mode de vie et importance culturelle",
        descriptionDe: "Kunst, Essen, Lebensstil und kulturelle Bedeutung",
        descriptionEs: "Arte, gastronomía, estilo de vida e importancia cultural",
        icon: "coffee",
      },
      {
        id: "modern-times",
        name: "Modern Times",
        nameNl: "Moderne Tijd",
        nameFr: "Époque moderne",
        nameDe: "Moderne Zeit",
        nameEs: "Tiempos modernos",
        description: "What the neighborhood looks like today and how it has evolved",
        descriptionNl: "Hoe de buurt er vandaag uitziet en hoe deze is geëvolueerd",
        descriptionFr: "À quoi ressemble le quartier aujourd'hui et comment il a évolué",
        descriptionDe: "Wie das Viertel heute aussieht und wie es sich entwickelt hat",
        descriptionEs: "Cómo se ve el barrio hoy y cómo ha evolucionado",
        icon: "trending-up",
      },
      {
        id: "walking-tour",
        name: "Walking Tour",
        nameNl: "Wandeltour",
        nameFr: "Visite à pied",
        nameDe: "Rundgang",
        nameEs: "Paseo guiado",
        description: "A guided walk past the best and most famous places in the area",
        descriptionNl: "Een begeleide wandeling langs de beste en beroemdste plekken in het gebied",
        descriptionFr: "Une promenade guidée devant les meilleurs et les plus célèbres endroits du quartier",
        descriptionDe: "Ein geführter Spaziergang an den besten und berühmtesten Orten der Gegend vorbei",
        descriptionEs: "Un paseo guiado por los mejores y más famosos lugares de la zona",
        icon: "navigation",
      },
    ],
    topics: [
      {
        id: "ams-jordaan",
        name: "De Jordaan",
        nameNl: "De Jordaan",
        nameFr: "Le Jordaan",
        nameDe: "Die Jordaan",
        nameEs: "El Jordaan",
        description: "From working-class neighborhood to the most desirable area of Amsterdam",
        descriptionNl: "Van arbeidersbuurt tot de meest begeerde wijk van Amsterdam",
        descriptionFr: "De quartier ouvrier au quartier le plus convoité d'Amsterdam",
        descriptionDe: "Vom Arbeiterviertel zum begehrtesten Stadtteil von Amsterdam",
        descriptionEs: "De barrio obrero al área más deseada de Ámsterdam",
      },
      {
        id: "ams-de-pijp",
        name: "De Pijp",
        nameNl: "De Pijp",
        nameFr: "Le Pijp",
        nameDe: "De Pijp",
        nameEs: "De Pijp",
        description: "Albert Cuyp Market, Heineken, and multicultural Amsterdam",
        descriptionNl: "Albert Cuypmarkt, Heineken en multicultureel Amsterdam",
        descriptionFr: "Le marché Albert Cuyp, Heineken et l'Amsterdam multiculturel",
        descriptionDe: "Albert-Cuyp-Markt, Heineken und das multikulturelle Amsterdam",
        descriptionEs: "El mercado Albert Cuyp, Heineken y el Ámsterdam multicultural",
      },
      {
        id: "ams-noord",
        name: "Amsterdam-Noord",
        nameNl: "Amsterdam-Noord",
        nameFr: "Amsterdam-Nord",
        nameDe: "Amsterdam-Nord",
        nameEs: "Ámsterdam-Norte",
        description: "From industrial area to the hippest neighborhood in the city",
        descriptionNl: "Van industriegebied tot hipste buurt van de stad",
        descriptionFr: "De zone industrielle au quartier le plus branché de la ville",
        descriptionDe: "Vom Industriegebiet zum angesagtesten Stadtteil",
        descriptionEs: "De zona industrial al barrio más moderno de la ciudad",
      },
      {
        id: "ams-de-wallen",
        name: "De Wallen",
        nameNl: "De Wallen",
        nameFr: "Le Quartier Rouge",
        nameDe: "De Wallen",
        nameEs: "De Wallen",
        description: "Amsterdam's oldest and most talked-about neighborhood",
        descriptionNl: "Amsterdams oudste en meest besproken buurt",
        descriptionFr: "Le quartier le plus ancien et le plus controversé d'Amsterdam",
        descriptionDe: "Amsterdams ältestes und meistdiskutiertes Viertel",
        descriptionEs: "El barrio más antiguo y comentado de Ámsterdam",
      },
      {
        id: "ams-oud-west",
        name: "Oud-West & De Hallen",
        nameNl: "Oud-West & De Hallen",
        nameFr: "Oud-West & De Hallen",
        nameDe: "Oud-West & De Hallen",
        nameEs: "Oud-West y De Hallen",
        description: "Where old Amsterdam and new Amsterdam come together",
        descriptionNl: "Waar oud Amsterdam en nieuw Amsterdam samenkomen",
        descriptionFr: "Là où l'ancien et le nouveau Amsterdam se rencontrent",
        descriptionDe: "Wo das alte und das neue Amsterdam zusammenkommen",
        descriptionEs: "Donde el viejo y el nuevo Ámsterdam se encuentran",
      },
      {
        id: "ams-plantagebuurt",
        name: "The Plantage Quarter",
        nameNl: "De Plantagebuurt",
        nameFr: "Le Quartier Plantage",
        nameDe: "Das Plantage-Viertel",
        nameEs: "El Barrio Plantage",
        description: "Artis zoo, Hortus Botanicus, and forgotten stories",
        descriptionNl: "Artis, Hortus Botanicus en vergeten verhalen",
        descriptionFr: "Le zoo Artis, le Jardin botanique et des histoires oubliées",
        descriptionDe: "Artis Zoo, Hortus Botanicus und vergessene Geschichten",
        descriptionEs: "El zoo Artis, el Jardín Botánico y las historias olvidadas",
      },
      {
        id: "ams-zuid",
        name: "Amsterdam-Zuid",
        nameNl: "Amsterdam-Zuid",
        nameFr: "Amsterdam-Sud",
        nameDe: "Amsterdam-Süd",
        nameEs: "Ámsterdam-Sur",
        description: "Museum district, Vondelpark, and elegant boulevards",
        descriptionNl: "Museumkwartier, Vondelpark en elegante lanen",
        descriptionFr: "Le quartier des musées, le Vondelpark et les boulevards élégants",
        descriptionDe: "Museumsviertel, Vondelpark und elegante Boulevards",
        descriptionEs: "El barrio de los museos, Vondelpark y elegantes bulevares",
      },
      {
        id: "ams-bijlmer",
        name: "Bijlmer",
        nameNl: "Bijlmer",
        nameFr: "Bijlmer",
        nameDe: "Bijlmer",
        nameEs: "Bijlmer",
        description: "From utopian dream to multicultural neighborhood full of resilience",
        descriptionNl: "Van utopische droom tot multiculturele buurt vol veerkracht",
        descriptionFr: "Du rêve utopique au quartier multiculturel plein de résilience",
        descriptionDe: "Vom utopischen Traum zum multikulturellen Viertel voller Widerstandskraft",
        descriptionEs: "Del sueño utópico al barrio multicultural lleno de resiliencia",
      },
    ],
  },
  {
    id: "food-drinks",
    name: "Culinary",
    nameNl: "Culinair",
    nameFr: "Gastronomie",
    nameDe: "Kulinarisch",
    nameEs: "Gastronomía",
    icon: "restaurant",
    iconFamily: "MaterialIcons",
    iconImage: require("@/assets/images/category-culinary.png"),
    color: "#E67E22",
    topics: [
      {
        id: "ams-brown-cafe",
        name: "The Amsterdam Brown Café",
        nameNl: "Het Amsterdamse Bruin Café",
        nameFr: "Le Café Brun d'Amsterdam",
        nameDe: "Das Amsterdamer Braune Café",
        nameEs: "El Café Marrón de Ámsterdam",
        description: "Brown cafés and the art of gezelligheid",
        descriptionNl: "Bruine cafés en de kunst van gezelligheid",
        descriptionFr: "Les cafés bruns et l'art du gezelligheid",
        descriptionDe: "Braune Cafés und die Kunst der Gezelligheid",
        descriptionEs: "Los cafés marrones y el arte del gezelligheid",
      },
      {
        id: "ams-jenever",
        name: "Jenever: Dutch Gin",
        nameNl: "Jenever: Nederlands Nationaal Drankje",
        nameFr: "Le Genièvre : Le Gin Néerlandais",
        nameDe: "Jenever: Niederländischer Gin",
        nameEs: "Jenever: La Ginebra Holandesa",
        description: "The history and craft of the Netherlands' national spirit",
        descriptionNl: "De geschiedenis en het ambacht van Nederlands nationale drank",
        descriptionFr: "L'histoire et l'artisanat de la boisson nationale des Pays-Bas",
        descriptionDe: "Die Geschichte und das Handwerk des niederländischen Nationalgetränks",
        descriptionEs: "La historia y el oficio de la bebida nacional de los Países Bajos",
      },
      {
        id: "ams-cheese",
        name: "Dutch Cheese",
        nameNl: "Hollandse Kaas",
        nameFr: "Le Fromage Hollandais",
        nameDe: "Holländischer Käse",
        nameEs: "Queso Holandés",
        description: "From Gouda to old Amsterdam: the cheese culture",
        descriptionNl: "Van Gouda tot Oude Amsterdam: de kaascultuur",
        descriptionFr: "Du Gouda au vieil Amsterdam : la culture du fromage",
        descriptionDe: "Von Gouda bis Alter Amsterdam: die Käsekultur",
        descriptionEs: "Del Gouda al viejo Ámsterdam: la cultura del queso",
      },
      {
        id: "ams-herring",
        name: "Herring & Fish",
        nameNl: "Haring & Vis",
        nameFr: "Le Hareng et le Poisson",
        nameDe: "Hering & Fisch",
        nameEs: "Arenque y Pescado",
        description: "The Hollandse Nieuwe and the fish trade that made Amsterdam great",
        descriptionNl: "De Hollandse Nieuwe en de vishandel die Amsterdam groot maakte",
        descriptionFr: "Le Hollandse Nieuwe et le commerce du poisson qui a fait la grandeur d'Amsterdam",
        descriptionDe: "Die Hollandse Nieuwe und der Fischhandel, der Amsterdam groß machte",
        descriptionEs: "El Hollandse Nieuwe y el comercio de pescado que hizo grande a Ámsterdam",
      },
      {
        id: "ams-heineken",
        name: "The Heineken Legacy",
        nameNl: "De Heineken-Erfenis",
        nameFr: "L'Héritage Heineken",
        nameDe: "Das Heineken-Erbe",
        nameEs: "El Legado Heineken",
        description: "Brewing beer in Amsterdam since 1864",
        descriptionNl: "Bier brouwen in Amsterdam sinds 1864",
        descriptionFr: "Brassage de bière à Amsterdam depuis 1864",
        descriptionDe: "Bierbrauen in Amsterdam seit 1864",
        descriptionEs: "Elaboración de cerveza en Ámsterdam desde 1864",
      },
      {
        id: "ams-rijsttafel",
        name: "The Indonesian Rijsttafel",
        nameNl: "De Indonesische Rijsttafel",
        nameFr: "Le Rijsttafel Indonésien",
        nameDe: "Die Indonesische Reistafel",
        nameEs: "El Rijsttafel Indonesio",
        description: "How the colonies enriched Amsterdam's cuisine",
        descriptionNl: "Hoe de koloniën de Amsterdamse keuken verrijkten",
        descriptionFr: "Comment les colonies ont enrichi la cuisine amsterdamoise",
        descriptionDe: "Wie die Kolonien die Amsterdamer Küche bereicherten",
        descriptionEs: "Cómo las colonias enriquecieron la cocina de Ámsterdam",
      },
      {
        id: "ams-coffee-culture",
        name: "Coffee Culture",
        nameNl: "Koffiecultuur",
        nameFr: "La Culture du Café",
        nameDe: "Kaffeekultur",
        nameEs: "Cultura del Café",
        description: "From the first coffee house to specialty coffee",
        descriptionNl: "Van het eerste koffiehuis tot specialty coffee",
        descriptionFr: "Du premier café au café de spécialité",
        descriptionDe: "Vom ersten Kaffeehaus bis zum Spezialitätenkaffee",
        descriptionEs: "Del primer café a la cafetería de especialidad",
      },
      {
        id: "ams-borrel-culture",
        name: "Borrel Culture & Bitterballen",
        nameNl: "Borrelcultuur & Bitterballen",
        nameFr: "La Culture du Borrel et les Bitterballen",
        nameDe: "Borrel-Kultur & Bitterballen",
        nameEs: "Cultura del Borrel y Bitterballen",
        description: "The Dutch tradition of borrel, the social snack hour",
        descriptionNl: "De Nederlandse traditie van het borrelen",
        descriptionFr: "La tradition néerlandaise du borrel, l'heure de l'apéritif social",
        descriptionDe: "Die niederländische Tradition des Borrelen, die gesellige Snack-Stunde",
        descriptionEs: "La tradición holandesa del borrel, la hora social del aperitivo",
      },
    ],
  },
];

const themesMap: Record<string, Theme[]> = {
  paris: parisThemes,
  amsterdam: amsterdamThemes,
};

export function getThemes(cityId?: string): Theme[] {
  if (cityId) {
    return themesMap[cityId] || parisThemes;
  }
  const config = getCityConfigSync();
  return themesMap[config.id] || parisThemes;
}

export const themes = parisThemes;

export interface PodcastLength {
  id: string;
  name: string;
  nameNl: string;
  nameFr: string;
  nameDe: string;
  nameEs: string;
  duration: string;
  words: number;
}

export const podcastLengths: PodcastLength[] = [
  { id: "short", name: "Short", nameNl: "Kort", nameFr: "Court", nameDe: "Kurz", nameEs: "Corto", duration: "~3 min", words: 400 },
  { id: "long", name: "Long", nameNl: "Lang", nameFr: "Long", nameDe: "Lang", nameEs: "Largo", duration: "~8 min", words: 1100 },
];

export interface UserLevel {
  id: string;
  name: string;
  nameNl: string;
  nameFr: string;
  nameDe: string;
  nameEs: string;
  icon: string;
  minPodcasts: number;
  description: string;
  descriptionNl: string;
  descriptionFr: string;
  descriptionDe: string;
  descriptionEs: string;
}

export function getUserLevels(): UserLevel[] {
  return getCityConfigSync().userLevels.map((level) => ({
    id: level.id,
    name: level.name.en,
    nameNl: level.name.nl,
    nameFr: level.name.fr,
    nameDe: level.name.de,
    nameEs: level.name.es,
    icon: level.icon,
    minPodcasts: level.minPodcasts,
    description: level.description.en,
    descriptionNl: level.description.nl,
    descriptionFr: level.description.fr,
    descriptionDe: level.description.de,
    descriptionEs: level.description.es,
  }));
}

interface Localizable {
  name: string;
  nameNl: string;
  nameFr: string;
  nameDe: string;
  nameEs: string;
}

interface LocalizableWithDescription extends Localizable {
  description: string;
  descriptionNl: string;
  descriptionFr: string;
  descriptionDe: string;
  descriptionEs: string;
}

export function getLocalizedName(item: Localizable, language: string): string {
  switch (language) {
    case "nl": return item.nameNl;
    case "fr": return item.nameFr;
    case "de": return item.nameDe;
    case "es": return item.nameEs;
    default: return item.name;
  }
}

export function getLocalizedDescription(item: LocalizableWithDescription, language: string): string {
  switch (language) {
    case "nl": return item.descriptionNl;
    case "fr": return item.descriptionFr;
    case "de": return item.descriptionDe;
    case "es": return item.descriptionEs;
    default: return item.description;
  }
}

export function getUserLevel(podcastCount: number): UserLevel {
  const levels = getUserLevels();
  for (let i = levels.length - 1; i >= 0; i--) {
    if (podcastCount >= levels[i].minPodcasts) {
      return levels[i];
    }
  }
  return levels[0];
}

export function getNextLevel(podcastCount: number): UserLevel | null {
  const levels = getUserLevels();
  const currentLevel = getUserLevel(podcastCount);
  const currentIndex = levels.findIndex(l => l.id === currentLevel.id);
  if (currentIndex >= 0 && currentIndex < levels.length - 1) {
    return levels[currentIndex + 1];
  }
  return null;
}

export function checkLevelUp(oldCount: number, newCount: number): UserLevel | null {
  const oldLevel = getUserLevel(oldCount);
  const newLevel = getUserLevel(newCount);
  if (newLevel.id !== oldLevel.id) {
    return newLevel;
  }
  return null;
}
