-- Barcelona city seed data
-- Run: psql $DATABASE_URL < scripts/barcelona-seed.sql

INSERT INTO cities (id, name, country, app_name, bundle_id, contact_email, privacy_policy_date, localized_names, localized_country, top_level_name, user_levels, role_description, moderation_prompt_template, moderation_reject_template, walking_tour_perspective, modern_culture_perspective)
VALUES (
  'barcelona',
  'Barcelona',
  'Spain',
  'Barcelona Stories',
  'app.replit.barcelonastories',
  'vragen@greenhome.nl',
  '2026-04-20',
  '{"en":"Barcelona","nl":"Barcelona","fr":"Barcelone","de":"Barcelona","es":"Barcelona"}'::jsonb,
  '{"en":"Spain","nl":"Spanje","fr":"l''Espagne","de":"Spanien","es":"España"}'::jsonb,
  '{"en":"Barcelona Stories","nl":"Barcelona Stories","fr":"Barcelona Stories","de":"Barcelona Stories","es":"Barcelona Stories"}'::jsonb,
  '[{"id":"viajero","icon":"airplane","minPodcasts":0,"name":{"en":"Traveler","nl":"Reiziger","fr":"Voyageur","de":"Reisender","es":"Viajero"},"description":{"en":"Just getting started exploring Barcelona","nl":"Net begonnen met het verkennen van Barcelona","fr":"Vous commencez à explorer Barcelone","de":"Du fängst gerade an, Barcelona zu erkunden","es":"Acabas de empezar a explorar Barcelona"}},{"id":"explorer","icon":"compass","minPodcasts":5,"name":{"en":"Explorer","nl":"Ontdekker","fr":"Explorateur","de":"Entdecker","es":"Explorador"},"description":{"en":"Discovering the hidden stories of Barcelona","nl":"De verborgen verhalen van Barcelona ontdekken","fr":"À la découverte des histoires cachées de Barcelone","de":"Die verborgenen Geschichten von Barcelona entdecken","es":"Descubriendo las historias ocultas de Barcelona"}},{"id":"connoisseur","icon":"star","minPodcasts":15,"name":{"en":"Connoisseur","nl":"Kenner","fr":"Connaisseur","de":"Kenner","es":"Conocedor"},"description":{"en":"A true connoisseur of Catalan culture","nl":"Een echte kenner van de Catalaanse cultuur","fr":"Un vrai connaisseur de la culture catalane","de":"Ein wahrer Kenner der katalanischen Kultur","es":"Un verdadero conocedor de la cultura catalana"}},{"id":"barcelones","icon":"crown","minPodcasts":30,"name":{"en":"Barcelonés","nl":"Barcelonees","fr":"Barcelonais","de":"Barceloneser","es":"Barcelonés"},"description":{"en":"You know Barcelona like a true local","nl":"Je kent Barcelona als een echte local","fr":"Vous connaissez Barcelone comme un vrai local","de":"Du kennst Barcelona wie ein wahrer Einheimischer","es":"Conoces Barcelona como un verdadero local"}}]'::jsonb,
  '{"nl": "Je bent een deskundige solo-podcastverteller. Je bent een ervaren gids die met de luisteraar door Barcelona wandelt. Je vertelstijl is warm maar nuchter. Je deelt feiten en achtergronden op een toegankelijke, ontspannen manier. Je schrijft in vloeiend, natuurlijk Nederlands.", "fr": "Vous etes un narrateur de podcast solo expert. Vous etes un guide experimente qui marche dans Barcelone avec l''auditeur. Votre style est chaleureux mais ancre dans les faits. Vous partagez des faits et du contexte de maniere accessible et detendue. Vous ecrivez en francais fluide et naturel.", "de": "Du bist ein sachkundiger Solo-Podcast-Erzaehler. Du bist ein erfahrener Guide, der mit dem Zuhoerer durch Barcelona spaziert. Dein Stil ist warm, aber sachlich. Du teilst Fakten und Hintergruende auf zugaengliche, entspannte Weise. Du schreibst in fliessendem, natuerlichem Deutsch.", "es": "Eres un narrador experto de podcast en solitario. Eres un guia experimentado que camina por Barcelona con el oyente. Tu estilo es calido pero basado en hechos. Compartes datos y contexto de manera accesible y relajada. Escribes en espanol fluido y natural.", "en": "You are a knowledgeable solo podcast storyteller. You are an experienced guide walking through Barcelona with the listener. Your style is warm but grounded. You share facts and context in an accessible, relaxed way. You write in fluent, natural English."}'::jsonb,
  'You are a content moderator for a city podcast app about {city}, {country}. Determine if the following topic is appropriate.\n\nALLOW topics that are: related to {city} or {country} in any way, including local streets, squares, neighborhoods, parks, landmarks, buildings, museums, restaurants, people, events, traditions, culture, history, architecture, food, nature, or daily life. Also allow general travel, culture, and lifestyle topics. Be GENEROUS — if a topic could reasonably be about {city} or {country}, allow it.\n\nREJECT ONLY topics that are: sexually explicit, promoting violence or hate, about illegal activities, about weapons or drugs.\n\nTopic: "{subject}"\n\nRespond with ONLY "ALLOW" or "REJECT".',
  'This topic is not suitable for {appName}. Please choose a topic related to {city}, its culture, history, or daily life.',
  '{"en": "Guide the listener as if walking through Barcelona together. Describe what they would see, hear, and smell along the boulevards, through the Gothic Quarter''s narrow alleys, past Gaudí''s curving facades, and along the Mediterranean. Take them to the best and most famous places in the area. Use directional language and vivid sensory details.", "nl": "Begeleid de luisteraar alsof je samen door Barcelona wandelt. Beschrijf wat ze zouden zien, horen en ruiken langs de boulevards, door de smalle straatjes van de Gotische Wijk, langs Gaudí''s golvende gevels en aan de Middellandse Zee. Neem ze mee naar de beste en beroemdste plekken in het gebied. Gebruik richtinggevende taal en levendige zintuiglijke details.", "fr": "Guidez l''auditeur comme si vous marchiez ensemble dans Barcelone. Decrivez ce qu''il verrait, entendrait et sentirait le long des boulevards, dans les ruelles du Quartier Gothique, devant les facades ondulantes de Gaudi et au bord de la Mediterranee. Emmenez-le aux meilleurs endroits et aux plus celebres du quartier. Utilisez un langage directionnel et des details sensoriels vivants.", "de": "Fuehre den Zuhoerer, als wuerdet ihr gemeinsam durch Barcelona spazieren. Beschreibe, was er entlang der Boulevards, durch die engen Gassen des Gotischen Viertels, an Gaudis geschwungenen Fassaden vorbei und am Mittelmeer sehen, hoeren und riechen wuerde. Nimm ihn mit zu den besten und beruehmtesten Orten der Gegend. Verwende Richtungsangaben und lebendige sensorische Details.", "es": "Guia al oyente como si caminaran juntos por Barcelona. Describe lo que veria, escucharia y oleria a lo largo de las ramblas, por las callejuelas del Barrio Gotico, frente a las fachadas onduladas de Gaudi y junto al Mediterraneo. Lleva al oyente a los mejores y mas famosos lugares de la zona. Usa lenguaje direccional y detalles sensoriales vividos."}'::jsonb,
  '{"en": "Focus on contemporary culture, modern-day significance, current trends, and how this topic connects to life in Barcelona today. Consider Barcelona''s role as a Mediterranean creative capital with a vibrant Catalan identity, design scene, and innovative spirit.", "nl": "Focus op hedendaagse cultuur, de moderne betekenis, huidige trends en hoe dit onderwerp aansluit bij het leven in Barcelona vandaag. Denk aan Barcelona''s rol als mediterrane creatieve hoofdstad met een levendige Catalaanse identiteit, designscene en innovatieve geest.", "fr": "Concentrez-vous sur la culture contemporaine, la signification moderne, les tendances actuelles et comment ce sujet se connecte a la vie a Barcelone aujourd''hui. Considerez le role de Barcelone comme capitale creative mediterraneenne avec une identite catalane vibrante.", "de": "Konzentriere dich auf zeitgenoessische Kultur, moderne Bedeutung, aktuelle Trends und wie dieses Thema mit dem Leben im heutigen Barcelona zusammenhaengt. Beruecksichtige Barcelonas Rolle als mediterrane Kreativhauptstadt mit lebendiger katalanischer Identitaet.", "es": "Concentrate en la cultura contemporanea, la importancia moderna, las tendencias actuales y como este tema se conecta con la vida en la Barcelona de hoy. Considera el papel de Barcelona como capital creativa mediterranea con una vibrante identidad catalana."}'::jsonb
) ON CONFLICT (id) DO UPDATE SET
  role_description = EXCLUDED.role_description,
  moderation_prompt_template = EXCLUDED.moderation_prompt_template,
  moderation_reject_template = EXCLUDED.moderation_reject_template,
  walking_tour_perspective = EXCLUDED.walking_tour_perspective,
  modern_culture_perspective = EXCLUDED.modern_culture_perspective,
  user_levels = EXCLUDED.user_levels,
  localized_names = EXCLUDED.localized_names,
  localized_country = EXCLUDED.localized_country,
  top_level_name = EXCLUDED.top_level_name;
